<!-- oip-layout-map-view.phtml -->
<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-group/oip-container-navbar.txt' ?>
<div class="container">
    <!-- oip-container-map-focus-view.txt -->
    <section id="container-focus" class="container well"><!-- change -->
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    </section>
    <!-- oip-container-latest-collection.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-container-latest-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <!-- oip-container-about-collection.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-container-blog.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
        <?php include '../oip-containers/oip-container-blog-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
    </section>
   <!-- oip-container-blog-collection.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-public-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <!-- oip-container-groups-collection.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-container-groups-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupSummaryContainer  -->
        <?php include '../oip-containers/oip-container-groups-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupSummaryContainer  -->
    </section>
    <!-- oip-container-activities-collection.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-container-activities-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer  -->
        <?php include '../oip-containers/oip-container-activities-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer  -->
    </section>
    <!-- oip-container-footer.txt -->
    <section class="container well">
        <?php include '../oip-containers/oip-container-footer.txt' ?>
    </section>
</div>


<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
<!-- end oip-layout-map-view.phtml -->
