<!-- oip-blog-layout.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>
<!-- end navbar -->
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-blog-primary.txt' ?>
</div>
<div id="secondary" class="container">
<?php include '../oip-containers/oip-container-map-services-secondary.txt' ?>
<?php include '../oip-containers/oip-container-calendar-secondary.txt' ?>
	<!-- fixed -->
<?php include '../oip-containers/oip-container-about-secondary.txt' ?>
<?php include '../oip-containers/oip-container-account-secondary.txt' ?>
	<!-- required -->
<?php include '../oip-containers/oip-footer.txt' ?>
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals & javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals & javascript -->
</body>
</html>
<!-- end oip-blog-layout.txt -->
