<!-- oip-layout-map-view.phtml -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.NavBarContainer  -->
<div class="container">
	<section id="container-focus" class="container marketing well" > 
<?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
	</section>
	<section class="container-summary"> 
<?php include '../oip-containers/oip-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
	</section>
	<section class="container-summary"> 
<?php include '../oip-containers/oip-container-groups-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupsContainer  -->
	</section>
	<section class="container-summary"> 
<?php include '../oip-containers/oip-container-activities-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitiesContainer  -->
	</section> 
	<section class="container-summary"> 
<?php include '../oip-containers/oip-container-footer.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.FooterContainer  -->
	</section> 
</div>

<!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-map-view.phtml -->
