<!-- oip-layout-error-view.phtml -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!--UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.NavbarContainer  -->
<!-- end navbar -->
<div class="container">
	<section id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-error-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapFocusViewCollection-->
	</section>
	<section class="container">
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.FooterContainer  -->
	</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-error-view.phtml -->
