<!-- oip-layout-map-view.phtml -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!--UseInformationObjectAsRoot:NavbarContainer  -->
<!-- end navbar -->
<div class="container">
<!-- section -->
	<section id="gridSystem"> 
<!-- container -->
	<div id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:MapFocusViewCollection-->
	</div>
	<div id="summary" class="container">
<!-- required -->
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:FooterContainer  -->
	</div>
<!-- end container -->
	</section> 
<!-- end section -->
</div>
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-map-view.phtml -->
