<!-- oip-layout-account-edit -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50" class="edit">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:NavigationContainer -->
<!-- end navbar -->
<div class="container">
	<section id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-account-focus-edit.txt' ?><!-- UseInformationObjectAsRoot:AccountContainer -->
	</section>
	<section class="container">
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:FooterContainer  -->
	</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-account-edit.txt -->
