<!-- oip-layout-account-view.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:NavigationContainer -->
<!-- end navbar -->
<div class="container">
<!-- section -->
	<section id=""> 
<!-- container -->
	<div id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-account-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AccountContainer -->
	</div>
	<div id="summary" class="container">
<!-- required -->
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:FooterContainer  -->
	</div>
<!-- end container -->
	</section> 
<!-- end section -->
</div>
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-account-view.txt -->
