<!-- oip-layout-calendar-edit.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?><!--UseInformationObjectAsRoot:Aalto.OIP.JavascriptContainer  -->
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50" >
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:Aalto.OIP.NavigationContainer -->
<!-- end navbar -->
<div class="container">
	<section id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-calendar-focus-edit.txt' ?><!-- UseInformationObjectAsRoot:Aalto.OIP.CalendarContainer -->
	</section>
	<section class="container">
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:Aalto.OIP.FooterContainer  -->
	</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?><!--UseInformationObjectAsRoot:Aalto.OIP.JavascriptContainer  -->
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-calendar-edit.txt -->
