<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>
<!-- end navbar -->
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container-fluid marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-template-primary.txt' ?>:BindItem=map-primary<!-- map -->
</div>
<div id="secondary" class="container">
	<?php include '../oip-containers/oip-container-template-secondary.txt' ?>BindItem=calendar-secondary<!-- calendar -->
	<?php include '../oip-containers/oip-container-template-secondary.txt' ?>BindItem=blog-secondary<!-- blog -->
	<?php include '../oip-containers/oip-container-template-secondary.txt' ?>BindItem=about-secondary<!-- about -->
	<?php include '../oip-containers/oip-container-template-secondary.txt' ?>BindItem=account-secondary<!-- account -->
	<!-- required -->
<?php include '../oip-containers/oip-footer.txt' ?>
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals & javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals & javascript -->
</body>
</html>