<!DOCTYPE html>
<html lang="en">
<?php include 'oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>

<!--the container class sets the width of the container and centers it -->

<!-- section -->
<section id="gridSystem">
<!-- maps & container-fluid -->
<div id="maps" class="container-fluid">
	<?php include'../oip-modules/oip-map.txt' ?>
	<?php include'../oip-modules/oip-zoom-panel.txt' ?>
	<?php include'../oip-modules/oip-control-panel-new.txt' ?>
</div>
<!-- end maps & container-fluid -->
<!-- communication & container -->
<div id="communication" class="container">
	<?php include '../oip-modules/oip-explanation.txt' ?>
	<?php include '../oip-modules/oip-blog.txt' ?>
</div>
<!-- end communication & container -->
<!-- bottom & container -->
<div id="bottom" class="container">
	<?php include'oip-account.txt' ?>
	<?php include'oip-footer.txt' ?>
</div>
<!-- bottom & container -->
<?php include '../oip-modules/oip-modals.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- bottom & container -->

</section><!-- end section -->

</body>
</html>