<!DOCTYPE html>
<html lang="en">
<!-- head -->
	<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
	<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>
<!-- end navbar -->
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container-fluid marketing">
	<?php include'../oip-containers/oip-map-services.txt' ?>
</div>
<div id="secondary" class="container">
	<?php include'../oip-containers/oip-edit-about.txt' ?>
	<?php include'../oip-containers/oip-blog.txt' ?>
	<?php include'../oip-containers/oip-account.txt' ?>
	<?php include'../oip-containers/oip-footer.txt' ?>
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals javascript -->
	<?php include '../oip-modules/oip-modals.txt' ?>
	<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals javascript -->
</body>
</html>