<!-- oip-layout-personal-view.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-containers/oip-container-navbar.txt' ?>
<div class="container">
	<section id="container-focus" class="container marketing well" >
<?php include '../oip-containers/oip-container-personal-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.PersonalContainer -->
	</section>
	<section class="container-summary">
<?php include '../oip-containers/oip-container-footer.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.FooterContainer  -->
	</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-personal-view.txt -->
