<!-- oip-layout-blog-more.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include '../oip-modules/oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-containers/oip-container-navbar.txt' ?>
<div class="container">
<!-- oip-container-blog-focus-view.txt -->
<section id="container-focus" class="container well" >
<?php include '../oip-containers/oip-container-blog-more.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer -->
</section>
<!-- oip-container-footer.txt -->
<section class="container-summary">
<?php include '../oip-containers/oip-container-footer.txt' ?>
</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-blog-more.txt -->
