<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>
<!-- end navbar -->
<!-- section -->
<section id="gridSystem">
<!-- services container-fluid -->
<div id="services" class="container-fluid">
	<?php include'../oip-modules/oip-map.txt' ?>
	<?php include'../oip-modules/oip-zoom-panel.txt' ?>
	<?php include'../oip-modules/oip-control-panel.txt' ?>
</div>
<!-- end services container-fluid -->
<div class="container">
<!-- secondaries -->
<div class="marketing">
	<?php include'../oip-modules/oip-explanation.txt' ?>
	<?php include'../oip-modules/oip-blog.txt' ?>
	<?php include'../oip-modules/oip-account.txt' ?>
	<?php include'../oip-modules/oip-footer.txt' ?>
</div>
<!-- end secondaries -->
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals javascript -->
</body>
</html>