<!-- oip-layout-groups-edit.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.NavBarContainer -->
<div class="container">
	<section id="container-focus" class="container marketing well" >
<?php include '../oip-containers/oip-container-groups-focus-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupContainer -->
	</section>
	<section class="container-summary">
<?php include '../oip-containers/oip-container-footer.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.FooterContainer  -->
	</section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-groups-edit.txt -->
