<!DOCTYPE html>
<html lang="en">
<body>
				<ul class="nav pull-right">
					<li><a href="oip-layouts/oip-layout-about.phtml">About</a></li>
					<li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Login<b class="caret"></b></a> 
					<ul class="dropdown-menu">
					<ul style="list-style-type: none;">
						<li><a href="/TheBallLogin.aspx?idprovider=openid"><i class="icon-oip-openid"></i>OpenID</a></li>
						<li><a href="/TheBallLogin.aspx?idprovider=google"><i class="icon-oip-google"></i>Google</a></li>
						<li><a href="/TheBallLogin.aspx?idprovider=yahoo"><i class="icon-oip-yahoo"></i>Yahoo</a></li>
						<li><a href="/TheBallLogin.aspx?idprovider=twitter"><i class="icon-oip-twitter"></i>Twitter</a></li>
						<li><a href="/TheBallLogin.aspx?idprovider=facebook"><i class="icon-oip-facebook"></i>Facebook</a></li>
					</ul>
				</ul>
				</ul>

</body>
</html>