<!-- oip-blog-layout.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?>
<!-- end navbar -->
<div class="container">
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="focus" class="container marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-account-focus.txt' ?><!-- UseInformationObjectAsRoot:AccountContainer -->
</div>
<div id="secondary" class="container">
	<!-- required -->
<?php include '../oip-containers/oip-container-footer.txt' ?>
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals & javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
</div>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals & javascript -->
</body>
</html>
<!-- end oip-blog-layout.txt -->
