<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?>
<!-- end navbar -->
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container-fluid marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-map-services-primary.txt' ?>:binding=container-map-services-primary<!-- container-map-services-primary -->
</div>
<div id="secondary" class="container">
<?php include '../oip-containers/oip-container-calendar-secondary.txt' ?>:binding=container-calendar-secondary<!--container-calendar-secondary -->
<?php include '../oip-containers/oip-container-blog-secondary.txt' ?>:binding=container-blog-secondary<!--container-blog-secondary -->
	<!-- fixed -->
<?php include '../oip-containers/oip-container-about-secondary.txt' ?>:binding=container-about-secondary<!--container-about-secondary -->
<?php include '../oip-containers/oip-container-account-secondary.txt' ?>:binding=container-account-secondary<!--container-account-secondary -->
	<!-- required -->
<?php include '../oip-containers/oip-footer.txt' ?>
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals & javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals & javascript -->
</body>
</html>