<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-modules/oip-navbar-fixed-top.txt' ?><!--UseInformationObjectAsRoot:NavbarContainer  -->
<!-- end navbar -->
<div class="container">
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="focus" class="container-fluid marketing well" style="margin-top:0px;background-color:white">
<?php include '../oip-containers/oip-container-map-services-primary.txt' ?><!-- UseInformationObjectAsRoot:MapCollection-->
</div>
<div id="secondary" class="container">
<?php include '../oip-containers/oip-container-blog-secondary.txt' ?><!--UseInformationObjectAsRoot:BlogContainer -->
<?php include '../oip-containers/oip-container-calendar-secondary.txt' ?><!--UseInformationObjectAsRoot:CalendarContainer -->
<?php include '../oip-containers/oip-container-projects-secondary.txt' ?><!--UseInformationObjectAsRoot:ProjectContainer -->
	<!-- fixed -->
<?php include '../oip-containers/oip-container-about-secondary.txt' ?><!--UseInformationObjectAsRoot:AboutContainer -->
<?php include '../oip-containers/oip-container-account-secondary.txt' ?><!--UseInformationObjectAsRoot:AccountContainer  -->
	<!-- required -->
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:FooterContainer  -->
</div>
<!-- end container -->
</section>
<!-- end section -->
<!-- modals & javascript -->
<?php include '../oip-modules/oip-modals.txt' ?>
</div>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end modals & javascript -->
</body>
</html>