<!-- oip-layout-error-view.phtml -->
<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar.txt' ?>
<div class="container">
	<section id="container-focus" class="container well" >
<?php include '../oip-containers/oip-container-error-focus-view.txt' ?>
	</section>
		<section class="container well"> 
<?php include '../oip-containers/oip-container-footer.txt' ?>
	</section>
</div>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
<!-- end oip-layout-error-view.phtml -->
