
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/oip-bootstrap.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/bootstrap-responsive.css" rel="stylesheet">

    <!--  <link href="../bootstrap-default/assets/css/jdpicker.css" rel="stylesheet">-->
    <!--Extra Styles from jQuery UI-->
    <!--  <link href="../third-party/jquery-ui/css/demo.css" rel="stylesheet">
      <link href="../third-party/jquery-ui/css/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet"> -->
    <!-- calendar -->
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../oip-additions/oip-assets/oip-images/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-114x114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-72x72.png">
    <link rel="apple-touch-icon-precomposed" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-57x57.png">
    <script src="../oip-additions/oip-assets/oip-js/jquery.js"></script>
    <script src="../oip-additions/oip-assets/oip-js/jquery.form.js"></script>
    <script src="../oip-additions/oip-assets/oip-js/OpenLayers.js"></script>
    <script type="text/javascript" src="../oip-additions/oip-assets/oip-js/nicEdit.js"></script>
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">

<!-- ========== Begin: oip-group\oip-container-navbar-group.txt ========== -->
<!-- start oip-container-navbar-group.txt -->
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container oip-navbar">
            <ul class="nav">
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown"">
                    <span style="">Aalto Global Impact</span>
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="../www-public/oip-layout-activities-summary.phtml">Homepage</a></li>
                        <li><a href="../www-public/oip-layout-map.phtml">Map</a></li>
                        <li><a href="../www-public/oip-layout-news.phtml">News</a></li>
                        <li><a href="../www-public/oip-layout-about.phtml">About</a></li>
                        <li><a href="../www-public/oip-layout-activities-summary.phtml"style="border: none;">Activities</a></li>
                    </ul>
                </li>
            </ul>
            </php><!-- navigation to www.aaltoglobalimpact.org -->

            <!-- ========== Begin: oip-group\../oip-modules/oip-module-group-nav-right.txt ========== -->
            <!-- start oip-module-nav-right.txt -->
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-user oip-account"></i>
                            My Account
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/auth/account/website/oip-account/oip-layout-account-welcome.phtml">My Welcome Page</a></li>
                            <li><a href="/auth/account/website/oip-account/oip-layout-account-edit.phtml">My Profile</a></li>
                            <li class="divider"></li>
                            <li><a href="/TheBallLogin.aspx?SignOut=true">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- end oip-module-nav-right.txt -->
            <!-- ========== End: oip-group\../oip-modules/oip-module-group-nav-right.txt ========== -->
            </php><!-- edit and my account menus for the group sections-->
        </div>
    </div>
</div>
<div class="subnavbar">
    <div class="subnavbar-inner navbar-group-border navbar-group-background">
        <div class="container">
            <ul class="mainnav">
                <li class="account" style="border: none">
                    <a href="" style="background-image: url(../oip-additions/oip-assets/oip-images/ui/oip-group-navbar-background.png);width: 200px"></a>
                </li>
                <li class="dropdown group-name">
                    <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.GroupContainer -->

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="/auth/grp/9798daca-afc4-4046-a99b-d0d88bb364e0/AaltoGlobalImpact.OIP/MediaContent/3c972870-aec2-40b6-b6c9-800f21f1c85b.png" width="32" height="32" alt="" class="img-polaroid" style="vertical-align:inherit;margin-top: 6px;height: 34px;width: 34px;margin-bottom: 0px;padding: 1px">
                        <span style=""> www.aaltoglobalimpact.org</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <a href="oip-layout-groups-edit.phtml"> Edit this group</a> </li>
                    </ul>

                    <!-- THEBALL-CONTEXT-END:* -->
                </li>
                </li>
                <li>
                    <a href="oip-layout-map.phtml">
                        <i class="icon-map-marker oip-map"></i>
                        <span>Map</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-book oip-news"></i>
                        <span>News</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <a href="oip-layout-blog-summary.phtml"> Summary of News Articles</a> </li>
                        <li> <a href="#add-blog" data-toggle="modal"> Add News Article</a> </li>
                    </ul>
                </li>
                <li>
                    <a href="oip-layout-about.phtml" class="dropdown-toggle">
                        <i class="icon-umbrella oip-about"></i>
                        <span>About this group</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-bullhorn oip-activity"></i>
                        <span>Activities</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <a href="oip-layout-activities-summary.phtml"> Summary</a> </li>
                        <li> <a href="#add-activity" data-toggle="modal"> Add New Activity</a> </li>
                        <!--<li class="divider"></li>
                        <li><a href="oip-layout-activities-summary.phtml"> My activities</a> </li>
                        <li class="divider"></li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#">Activities in Group A</a>
                            <ul class="dropdown-menu">
                                <li> <a href="#add-activity" data-toggle="modal"> Add</a> </li>
                                <li class="divider"></li>
                                <li><a tabindex="-1" href="#">Activity A-A</a></li>
                                <li><a tabindex="-1" href="#">Activity A-B</a></li>
                                <li><a tabindex="-1" href="#">Activity A-C</a></li>
                                <li><a tabindex="-1" href="#">Activity A-D</a></li>
                                <li><a tabindex="-1" href="#">Activity A-E</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#">Activities in Group B</a>
                            <ul class="dropdown-menu">
                                <li> <a href="#add-activity" data-toggle="modal"> Add</a> </li>
                                <li class="divider"></li>
                                <li><a tabindex="-1" href="#">Activity B-A</a></li>
                                <li><a tabindex="-1" href="#">Activity B-B</a></li>
                                <li><a tabindex="-1" href="#">Activity B-C</a></li>
                                <li><a tabindex="-1" href="#">Activity B-D</a></li>
                                <li><a tabindex="-1" href="#">Activity B-E</a></li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#">Activities in Group C <span class="badge badge-info">5</span></a>
                            <ul class="dropdown-menu">
                                <li> <a href="#add-activity" data-toggle="modal"> Add</a> </li>
                                <li class="divider"></li>
                                <li><a tabindex="-1" href="#">Activity C-A <span class="badge badge-success">2</span></a></li>
                                <li><a tabindex="-1" href="#">Activity C-B</a></li>
                                <li><a tabindex="-1" href="#">Activity C-C <span class="badge badge-warning">3</span></a></li>
                                <li><a tabindex="-1" href="#">Activity C-D</a></li>
                                <li><a tabindex="-1" href="#">Activity C-E</a></li>
                            </ul>
                        </li>  -->
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-globe oip-public"></i>
                        <span>Our Public Site</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <a href="../../publicsite/oip-public/oip-layout-landing.phtml"> Public Homepage</a> | <a href="../../wwwsite/www-public/oip-layout-landing.phtml"> Www</a> </li>
                        <li> <a href="../../publicsite/oip-public/oip-layout-map.phtml"> Public Map</a> | <a href="../../wwwsite/www-public/oip-layout-map.phtml"> Www</a> </li>
                        <li> <a href="../../publicsite/oip-public/oip-layout-blog.phtml"> Public Blog</a> | <a href="../../wwwsite/www-public/oip-layout-blog.phtml"> Www</a> </li>
                        <li> <a href="../../publicsite/oip-public/oip-layout-about.phtml"> Public About</a> | <a href="../../wwwsite/www-public/oip-layout-about.phtml"> Www</a> </li>
                        <li> <a href="../../publicsite/oip-public/oip-layout-activities-summary.phtml"> Public Activities</a> | <a href="../../wwwsite/www-public/oip-layout-activities-summary.phtml"> Www</a> </li>
                        <li class="divider"></li>
                        <li> <a href="#publishtogrouppublic" data-toggle="modal">Publish to Group Public Area</a></li>
                        <li> <a href="#publishtowww" data-toggle="modal">Publish to WWW</a></li>
                    </ul>
                </li>
            </ul>
        </div> <!-- /container -->
    </div> <!-- /subnavbar-inner -->
</div> <!-- /subnavbar -->

<!-- modals -->
<div id="add-activity" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Add an activity
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddActivityInfo:AddActivity -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddActivity" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="3aa91ed3-08aa-470d-ad0f-fdbaff79f6a8_ActivityName">Name of the activity</label>
                    <div class="controls">
                        <input name="3aa91ed3-08aa-470d-ad0f-fdbaff79f6a8_ActivityName" class="span4" id="3aa91ed3-08aa-470d-ad0f-fdbaff79f6a8_ActivityName" type="text" value="AddActivityInfo.ActivityName">
                    </div>
                </div>

                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>


<div id="add-blog" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Add a blog article
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddBlogPostInfo:AddBlogPost -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddBlogPost" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="8bfbf3f2-4220-4899-b908-dc1ea4c170d6_Title">Title of the blog article</label>
                    <div class="controls">
                        <input name="8bfbf3f2-4220-4899-b908-dc1ea4c170d6_Title" class="span4" id="8bfbf3f2-4220-4899-b908-dc1ea4c170d6_Title" type="text" value="">
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>

<div class="modal hide fade" id="publishtowww">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <p name="question" id="question">Publish the current www content to group-assigned www pages (www.aaltoglobalimpact.org)?</p>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">No</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="PublishGroupWwwContent">Yes!</button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="modal hide fade" id="publishtogrouppublic">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <p name="question" id="question">Publish the current public content to group public area (oip.aaltoglobalimpact.org)?</p>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">No</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="PublishGroupPublicContent">Yes!</button>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- end modals -->
<!-- end oip-container-navbar-group.txt -->
<!-- ========== End: oip-group\oip-container-navbar-group.txt ========== -->

<div class="container">
<section id="container-focus" class="container well" >

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.BlogContainer -->

<div class="services oip-news-header small">

    <!-- THEBALL-CONTEXT-OBJECT-BEGIN:Header -->

    <div class="hero-unit">
        <h1>
            <!-- start oip-atom-subtitle.txt -->
            <a data-id="a5ca9d7d-fe3c-49fa-a832-9872d7d07bb0_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
            <!-- end oip-atom-subtitle.txt -->


        </h1>
        <h1><small>
            <!-- start oip-atom-subtitle.txt -->
            <span class="small-before-after"/>"</span>
            <a data-id="a5ca9d7d-fe3c-49fa-a832-9872d7d07bb0_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">AGI Blogs</a>
            <span class="small-before-after"/>"</span>
            <!-- end oip-atom-subtitle.txt -->
        </small></h1>
    </div>



    <!-- THEBALL-CONTEXT-END:Header -->

</div>
<div class="row-fluid">
<div class="span3">

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:BlogIndexGroup -->

<p><img src="[!ATOM]Icon.ImageData.ContentUrl[ATOM]"></p>
<h4>
    <!-- start oip-atom-subtitle.txt -->
    <a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Blogs</a>
    <!-- end oip-atom-subtitle.txt -->


</h4>
<p><a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Introduction"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Blogs Introduction Text - In-context-edit this.<br></a>
</p>
<div class="accordion index" id="accordion-blog-index">
<div class="accordion-group accordion-group-index">
<div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-One">
        blogs by location
    </a>
</div>
<div id="collapse-accordion-blog-index-One" class="accordion-body collapse in">
<div class="accordion-inner accordion-group-index">
<ul class="unstyled">

<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:BlogByLocation -->


<li><a href="AaltoGlobalImpact.OIP.Blog_032960af-7073-494c-b739-ec01c6669ade_DefaultView.phtml"> Anne Badan</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_045e9d00-74b7-4ccb-b503-936362862cc5_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_0a5dcd1e-675e-4093-90f6-cdb14cc2462f_DefaultView.phtml"> Jeroen's new article via demooip.aalto...</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_187ff763-f5d6-4a45-928f-3fb1ced37639_DefaultView.phtml"> Peru: Innovation and Design for Furniture SMEs</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33b68341-3c2b-44ee-9bd6-6c433580d089_DefaultView.phtml"> LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_3457eac7-7677-402f-abb3-9735e8345ae8_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_37710489-a580-4535-99b7-68f6686cb547_DefaultView.phtml"> Our Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4e3289f4-1540-4bc6-a43d-22d256ccc96d_DefaultView.phtml"> Aalto Global Impact's guest lecture in October</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_50fd66f5-b0dd-4fc7-adaf-e90a312ecac1_DefaultView.phtml"> Riina Subra</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_566a6297-594d-4c9d-9fae-f730423fe986_DefaultView.phtml"> Aalto student talk</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_57461372-d0b9-4085-b82b-62b85ca36b14_DefaultView.phtml"> Uganda: Water, Sanitation and Hygiene</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b69e13b-110f-426b-8b20-1cdc068f546f_DefaultView.phtml"> GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5e425198-40f9-42e5-b643-08d98ef28a39_DefaultView.phtml"> Aalto Global Impact - UNICEF project newsletter</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7983bccb-e416-4df3-97c9-3eb67c5412f4_DefaultView.phtml"> Aalto Global Impact - to make the world a better place</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7cc8d059-5698-45de-bf2e-461680b7d388_DefaultView.phtml"> India and Sri Lanka: Rapid Development for Inclusive Innovation</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7d17fee0-482b-4e8e-8f8c-595ff9e1736c_DefaultView.phtml"> Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87493283-5cba-4715-bf2d-d5a2eb3f8753_DefaultView.phtml"> ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87a5294c-d304-4a63-b38b-08e63372296a_DefaultView.phtml"> Teija Lehtonen</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_8d7bf5d6-7a06-4001-931f-b2d52558e90f_DefaultView.phtml"> Andrew Clutterbuck</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_906187a2-0957-49d3-ba68-6613363c0578_DefaultView.phtml"> Aalto LAB Mexico, design for sustainability in the Maya community</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_90ca34e7-f4ca-48db-a720-7ef5e4fc4255_DefaultView.phtml"> Mozambique: Business Models for Local Producers</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9a739f07-2d32-451e-9143-387b5f36a37c_DefaultView.phtml"> Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9b4aabe5-0c25-4b87-9b31-ffdc43d4ac64_DefaultView.phtml"> Aalto Global Impact - internship announcement</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9ec49203-fd65-4fed-92c0-416a3f9b794e_DefaultView.phtml"> Social Impact through Creative Design - seminar</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a4789894-c044-4c0b-bda1-2f3d46c7641e_DefaultView.phtml"> PRESENT: South Africa: World Design Capital 2012-2014, Helsinki meets Cape Town</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a8faa7b4-9fd8-47a4-bbef-4691dd8ece49_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a94970d9-f376-418a-a867-cf0e463d520c_DefaultView.phtml"> Rahim Saatov</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b3214363-da13-41a1-a869-951ea0f01a94_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b9e733de-2f2c-403d-b42c-76463fcaae95_DefaultView.phtml"> test with Phil</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c1aec69c-a44c-494c-8bb4-c9443e6b6bb0_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c8750e1d-e39e-41f2-a54f-b616c7233b59_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT, 10-14 September, 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_ca8e6eb7-e292-4a3c-bed7-1632b43051df_DefaultView.phtml"> Jeroen's news of today 11 Dec 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_dcdd09da-b4c1-4b76-aebc-ff943a4d0c22_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_de514c87-4aad-424c-a1f5-4a01ae4c2f8c_DefaultView.phtml"> Safe and Sustainable Sanitation Workshop</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a056fe65-2e41-4e50-b971-edd777b5d9ec_DefaultView.phtml"> Blog.Title</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e1bc2fd4-d378-4432-8737-15d085ae08fa_DefaultView.phtml"> Sujil Kodathoor</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e9593457-4acf-49ea-bba8-bdeffd5416d2_DefaultView.phtml"> This is a OIP Scenario test Wed28 - 12:00pm </a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f2f41fb6-55b0-43ed-bccf-179e64113c2f_DefaultView.phtml"> Our Team</a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->

<li><a href="AaltoGlobalImpact.OIP.Blog_fdecde4e-e343-416a-8904-5ab08e4d0ad2_DefaultView.phtml"> F212 - Share your thoughts on the future – learn from others – have your ideas published – </a></li>


<!-- THEBALL-CONTEXT-END:BlogByLocation -->


</ul>
</div>
</div>
</div>
<div class="accordion-group accordion-group-index">
<div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Two">
        blogs by date
    </a>
</div>
<div id="collapse-accordion-blog-index-Two" class="accordion-body collapse">
<div class="accordion-inner accordion-group-index">
<ul class="unstyled">

<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:BlogByDate -->


<li><a href="AaltoGlobalImpact.OIP.Blog_032960af-7073-494c-b739-ec01c6669ade_DefaultView.phtml"> Anne Badan</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_045e9d00-74b7-4ccb-b503-936362862cc5_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_0a5dcd1e-675e-4093-90f6-cdb14cc2462f_DefaultView.phtml"> Jeroen's new article via demooip.aalto...</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_187ff763-f5d6-4a45-928f-3fb1ced37639_DefaultView.phtml"> Peru: Innovation and Design for Furniture SMEs</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33b68341-3c2b-44ee-9bd6-6c433580d089_DefaultView.phtml"> LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_3457eac7-7677-402f-abb3-9735e8345ae8_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_37710489-a580-4535-99b7-68f6686cb547_DefaultView.phtml"> Our Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4e3289f4-1540-4bc6-a43d-22d256ccc96d_DefaultView.phtml"> Aalto Global Impact's guest lecture in October</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_50fd66f5-b0dd-4fc7-adaf-e90a312ecac1_DefaultView.phtml"> Riina Subra</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_566a6297-594d-4c9d-9fae-f730423fe986_DefaultView.phtml"> Aalto student talk</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_57461372-d0b9-4085-b82b-62b85ca36b14_DefaultView.phtml"> Uganda: Water, Sanitation and Hygiene</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b69e13b-110f-426b-8b20-1cdc068f546f_DefaultView.phtml"> GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5e425198-40f9-42e5-b643-08d98ef28a39_DefaultView.phtml"> Aalto Global Impact - UNICEF project newsletter</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7983bccb-e416-4df3-97c9-3eb67c5412f4_DefaultView.phtml"> Aalto Global Impact - to make the world a better place</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7cc8d059-5698-45de-bf2e-461680b7d388_DefaultView.phtml"> India and Sri Lanka: Rapid Development for Inclusive Innovation</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7d17fee0-482b-4e8e-8f8c-595ff9e1736c_DefaultView.phtml"> Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87493283-5cba-4715-bf2d-d5a2eb3f8753_DefaultView.phtml"> ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87a5294c-d304-4a63-b38b-08e63372296a_DefaultView.phtml"> Teija Lehtonen</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_8d7bf5d6-7a06-4001-931f-b2d52558e90f_DefaultView.phtml"> Andrew Clutterbuck</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_906187a2-0957-49d3-ba68-6613363c0578_DefaultView.phtml"> Aalto LAB Mexico, design for sustainability in the Maya community</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_90ca34e7-f4ca-48db-a720-7ef5e4fc4255_DefaultView.phtml"> Mozambique: Business Models for Local Producers</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9a739f07-2d32-451e-9143-387b5f36a37c_DefaultView.phtml"> Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9b4aabe5-0c25-4b87-9b31-ffdc43d4ac64_DefaultView.phtml"> Aalto Global Impact - internship announcement</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9ec49203-fd65-4fed-92c0-416a3f9b794e_DefaultView.phtml"> Social Impact through Creative Design - seminar</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a4789894-c044-4c0b-bda1-2f3d46c7641e_DefaultView.phtml"> PRESENT: South Africa: World Design Capital 2012-2014, Helsinki meets Cape Town</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a8faa7b4-9fd8-47a4-bbef-4691dd8ece49_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a94970d9-f376-418a-a867-cf0e463d520c_DefaultView.phtml"> Rahim Saatov</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b3214363-da13-41a1-a869-951ea0f01a94_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b9e733de-2f2c-403d-b42c-76463fcaae95_DefaultView.phtml"> test with Phil</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c1aec69c-a44c-494c-8bb4-c9443e6b6bb0_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c8750e1d-e39e-41f2-a54f-b616c7233b59_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT, 10-14 September, 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_ca8e6eb7-e292-4a3c-bed7-1632b43051df_DefaultView.phtml"> Jeroen's news of today 11 Dec 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_dcdd09da-b4c1-4b76-aebc-ff943a4d0c22_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_de514c87-4aad-424c-a1f5-4a01ae4c2f8c_DefaultView.phtml"> Safe and Sustainable Sanitation Workshop</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a056fe65-2e41-4e50-b971-edd777b5d9ec_DefaultView.phtml"> Blog.Title</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e1bc2fd4-d378-4432-8737-15d085ae08fa_DefaultView.phtml"> Sujil Kodathoor</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e9593457-4acf-49ea-bba8-bdeffd5416d2_DefaultView.phtml"> This is a OIP Scenario test Wed28 - 12:00pm </a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f2f41fb6-55b0-43ed-bccf-179e64113c2f_DefaultView.phtml"> Our Team</a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->

<li><a href="AaltoGlobalImpact.OIP.Blog_fdecde4e-e343-416a-8904-5ab08e4d0ad2_DefaultView.phtml"> F212 - Share your thoughts on the future – learn from others – have your ideas published – </a></li>


<!-- THEBALL-CONTEXT-END:BlogByDate -->


</ul>
</div>
</div>
</div>
<div class="accordion-group accordion-group-index">
<div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Three">
        blogs by author
    </a>
</div>
<div id="collapse-accordion-blog-index-Three" class="accordion-body collapse">
<div class="accordion-inner accordion-group-index">
<ul class="unstyled">

<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:BlogByAuthor -->


<li><a href="AaltoGlobalImpact.OIP.Blog_032960af-7073-494c-b739-ec01c6669ade_DefaultView.phtml"> Anne Badan</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_045e9d00-74b7-4ccb-b503-936362862cc5_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_0a5dcd1e-675e-4093-90f6-cdb14cc2462f_DefaultView.phtml"> Jeroen's new article via demooip.aalto...</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_187ff763-f5d6-4a45-928f-3fb1ced37639_DefaultView.phtml"> Peru: Innovation and Design for Furniture SMEs</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33b68341-3c2b-44ee-9bd6-6c433580d089_DefaultView.phtml"> LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_3457eac7-7677-402f-abb3-9735e8345ae8_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_37710489-a580-4535-99b7-68f6686cb547_DefaultView.phtml"> Our Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4e3289f4-1540-4bc6-a43d-22d256ccc96d_DefaultView.phtml"> Aalto Global Impact's guest lecture in October</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_50fd66f5-b0dd-4fc7-adaf-e90a312ecac1_DefaultView.phtml"> Riina Subra</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_566a6297-594d-4c9d-9fae-f730423fe986_DefaultView.phtml"> Aalto student talk</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_57461372-d0b9-4085-b82b-62b85ca36b14_DefaultView.phtml"> Uganda: Water, Sanitation and Hygiene</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b69e13b-110f-426b-8b20-1cdc068f546f_DefaultView.phtml"> GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5e425198-40f9-42e5-b643-08d98ef28a39_DefaultView.phtml"> Aalto Global Impact - UNICEF project newsletter</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7983bccb-e416-4df3-97c9-3eb67c5412f4_DefaultView.phtml"> Aalto Global Impact - to make the world a better place</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7cc8d059-5698-45de-bf2e-461680b7d388_DefaultView.phtml"> India and Sri Lanka: Rapid Development for Inclusive Innovation</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7d17fee0-482b-4e8e-8f8c-595ff9e1736c_DefaultView.phtml"> Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87493283-5cba-4715-bf2d-d5a2eb3f8753_DefaultView.phtml"> ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87a5294c-d304-4a63-b38b-08e63372296a_DefaultView.phtml"> Teija Lehtonen</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_8d7bf5d6-7a06-4001-931f-b2d52558e90f_DefaultView.phtml"> Andrew Clutterbuck</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_906187a2-0957-49d3-ba68-6613363c0578_DefaultView.phtml"> Aalto LAB Mexico, design for sustainability in the Maya community</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_90ca34e7-f4ca-48db-a720-7ef5e4fc4255_DefaultView.phtml"> Mozambique: Business Models for Local Producers</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9a739f07-2d32-451e-9143-387b5f36a37c_DefaultView.phtml"> Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9b4aabe5-0c25-4b87-9b31-ffdc43d4ac64_DefaultView.phtml"> Aalto Global Impact - internship announcement</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9ec49203-fd65-4fed-92c0-416a3f9b794e_DefaultView.phtml"> Social Impact through Creative Design - seminar</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a4789894-c044-4c0b-bda1-2f3d46c7641e_DefaultView.phtml"> PRESENT: South Africa: World Design Capital 2012-2014, Helsinki meets Cape Town</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a8faa7b4-9fd8-47a4-bbef-4691dd8ece49_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a94970d9-f376-418a-a867-cf0e463d520c_DefaultView.phtml"> Rahim Saatov</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b3214363-da13-41a1-a869-951ea0f01a94_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b9e733de-2f2c-403d-b42c-76463fcaae95_DefaultView.phtml"> test with Phil</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c1aec69c-a44c-494c-8bb4-c9443e6b6bb0_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c8750e1d-e39e-41f2-a54f-b616c7233b59_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT, 10-14 September, 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_ca8e6eb7-e292-4a3c-bed7-1632b43051df_DefaultView.phtml"> Jeroen's news of today 11 Dec 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_dcdd09da-b4c1-4b76-aebc-ff943a4d0c22_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_de514c87-4aad-424c-a1f5-4a01ae4c2f8c_DefaultView.phtml"> Safe and Sustainable Sanitation Workshop</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a056fe65-2e41-4e50-b971-edd777b5d9ec_DefaultView.phtml"> Blog.Title</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e1bc2fd4-d378-4432-8737-15d085ae08fa_DefaultView.phtml"> Sujil Kodathoor</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e9593457-4acf-49ea-bba8-bdeffd5416d2_DefaultView.phtml"> This is a OIP Scenario test Wed28 - 12:00pm </a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f2f41fb6-55b0-43ed-bccf-179e64113c2f_DefaultView.phtml"> Our Team</a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->

<li><a href="AaltoGlobalImpact.OIP.Blog_fdecde4e-e343-416a-8904-5ab08e4d0ad2_DefaultView.phtml"> F212 - Share your thoughts on the future – learn from others – have your ideas published – </a></li>


<!-- THEBALL-CONTEXT-END:BlogByAuthor -->


</ul>
</div>
</div>
</div>
<div class="accordion-group accordion-group-index">
<div class="accordion-heading">
    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Four">
        blogs by category
    </a>
</div>
<div id="collapse-accordion-blog-index-Four" class="accordion-body collapse">
<div class="accordion-inner accordion-group-index">
<ul class="unstyled">

<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:BlogByCategory -->


<li><a href="AaltoGlobalImpact.OIP.Blog_032960af-7073-494c-b739-ec01c6669ade_DefaultView.phtml"> Anne Badan</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_045e9d00-74b7-4ccb-b503-936362862cc5_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_0a5dcd1e-675e-4093-90f6-cdb14cc2462f_DefaultView.phtml"> Jeroen's new article via demooip.aalto...</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_187ff763-f5d6-4a45-928f-3fb1ced37639_DefaultView.phtml"> Peru: Innovation and Design for Furniture SMEs</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33b68341-3c2b-44ee-9bd6-6c433580d089_DefaultView.phtml"> LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_3457eac7-7677-402f-abb3-9735e8345ae8_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_37710489-a580-4535-99b7-68f6686cb547_DefaultView.phtml"> Our Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4e3289f4-1540-4bc6-a43d-22d256ccc96d_DefaultView.phtml"> Aalto Global Impact's guest lecture in October</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_50fd66f5-b0dd-4fc7-adaf-e90a312ecac1_DefaultView.phtml"> Riina Subra</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_566a6297-594d-4c9d-9fae-f730423fe986_DefaultView.phtml"> Aalto student talk</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_57461372-d0b9-4085-b82b-62b85ca36b14_DefaultView.phtml"> Uganda: Water, Sanitation and Hygiene</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b69e13b-110f-426b-8b20-1cdc068f546f_DefaultView.phtml"> GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5e425198-40f9-42e5-b643-08d98ef28a39_DefaultView.phtml"> Aalto Global Impact - UNICEF project newsletter</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7983bccb-e416-4df3-97c9-3eb67c5412f4_DefaultView.phtml"> Aalto Global Impact - to make the world a better place</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7cc8d059-5698-45de-bf2e-461680b7d388_DefaultView.phtml"> India and Sri Lanka: Rapid Development for Inclusive Innovation</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7d17fee0-482b-4e8e-8f8c-595ff9e1736c_DefaultView.phtml"> Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87493283-5cba-4715-bf2d-d5a2eb3f8753_DefaultView.phtml"> ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87a5294c-d304-4a63-b38b-08e63372296a_DefaultView.phtml"> Teija Lehtonen</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_8d7bf5d6-7a06-4001-931f-b2d52558e90f_DefaultView.phtml"> Andrew Clutterbuck</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_906187a2-0957-49d3-ba68-6613363c0578_DefaultView.phtml"> Aalto LAB Mexico, design for sustainability in the Maya community</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_90ca34e7-f4ca-48db-a720-7ef5e4fc4255_DefaultView.phtml"> Mozambique: Business Models for Local Producers</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9a739f07-2d32-451e-9143-387b5f36a37c_DefaultView.phtml"> Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9b4aabe5-0c25-4b87-9b31-ffdc43d4ac64_DefaultView.phtml"> Aalto Global Impact - internship announcement</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9ec49203-fd65-4fed-92c0-416a3f9b794e_DefaultView.phtml"> Social Impact through Creative Design - seminar</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a4789894-c044-4c0b-bda1-2f3d46c7641e_DefaultView.phtml"> PRESENT: South Africa: World Design Capital 2012-2014, Helsinki meets Cape Town</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a8faa7b4-9fd8-47a4-bbef-4691dd8ece49_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a94970d9-f376-418a-a867-cf0e463d520c_DefaultView.phtml"> Rahim Saatov</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b3214363-da13-41a1-a869-951ea0f01a94_DefaultView.phtml"> </a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b9e733de-2f2c-403d-b42c-76463fcaae95_DefaultView.phtml"> test with Phil</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c1aec69c-a44c-494c-8bb4-c9443e6b6bb0_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c8750e1d-e39e-41f2-a54f-b616c7233b59_DefaultView.phtml"> Aalto - World Bank partnership: Training Program on Innovation Policy for ICT, 10-14 September, 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_ca8e6eb7-e292-4a3c-bed7-1632b43051df_DefaultView.phtml"> Jeroen's news of today 11 Dec 2012</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_dcdd09da-b4c1-4b76-aebc-ff943a4d0c22_DefaultView.phtml"> Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_de514c87-4aad-424c-a1f5-4a01ae4c2f8c_DefaultView.phtml"> Safe and Sustainable Sanitation Workshop</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a056fe65-2e41-4e50-b971-edd777b5d9ec_DefaultView.phtml"> Blog.Title</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e1bc2fd4-d378-4432-8737-15d085ae08fa_DefaultView.phtml"> Sujil Kodathoor</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_e9593457-4acf-49ea-bba8-bdeffd5416d2_DefaultView.phtml"> This is a OIP Scenario test Wed28 - 12:00pm </a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f2f41fb6-55b0-43ed-bccf-179e64113c2f_DefaultView.phtml"> Our Team</a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->

<li><a href="AaltoGlobalImpact.OIP.Blog_fdecde4e-e343-416a-8904-5ab08e4d0ad2_DefaultView.phtml"> F212 - Share your thoughts on the future – learn from others – have your ideas published – </a></li>


<!-- THEBALL-CONTEXT-END:BlogByCategory -->


</ul>
</div>
</div>
</div>
</div>
<p><a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Summary"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">BlogIndexGroup.Summary
    BlogIndexGroup.Summary
    BlogIndexGroup.Summary
    BlogIndexGroup.Summary
    BlogIndexGroup.Summary
</a>
</p>


<!-- THEBALL-CONTEXT-END:BlogIndexGroup -->

</div>
<div class="span9">

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

<div class="tabbable tabs-left">
<ul class="nav nav-tabs" style="margin-bottom:0px;">
    <li class="active"><a href="#tab-profile" data-toggle="tab">Blog article</a></li>
    <li><a href="#tab-images" data-toggle="tab">Images</a></li>
    <li><a href="#tab-locations-current" data-toggle="tab">Locations</a></li>
    <li><a href="#tab-category" data-toggle="tab">Category</a></li>
    <li><a href="#tab-delete" data-toggle="tab" class="delete">Delete Blog</a></li>
</ul>
<div class="tab-content tab-border">
<div class="tab-pane active" id="tab-profile"><div id="group-profile" class="span7" style=";margin-top:10px">
    <form id="" method="post" class="form-horizontal ">
        <!-- THEBALL-FORM-HIDDEN-FIELDS -->
        <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
        <fieldset id="">
            <div class="control-group">
                <label class="control-label" for="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Title">Title</label>
                <div class="controls">
                    <input name="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Title" class="input-xxlarge" id="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Title" type="text" value="Jeroen's news of today 11 Dec 2012">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="ca8e6eb7-e292-4a3c-bed7-1632b43051df_SubTitle">SubTitle</label>
                <div class="controls">
                    <input name="ca8e6eb7-e292-4a3c-bed7-1632b43051df_SubTitle" class="input-xxlarge" id="ca8e6eb7-e292-4a3c-bed7-1632b43051df_SubTitle" type="text" value="">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Body">Body</label>
                <div class="controls">
                    <textarea class="input-xxlarge" id="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Body" name="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Body" rows="20" placeholder="add org name"></textarea>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Excerpt">Excerpt</label>
                <div class="controls">
                    <textarea class="input-xxlarge" id="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Excerpt" name="ca8e6eb7-e292-4a3c-bed7-1632b43051df_Excerpt" rows="6" placeholder="add org name"></textarea>
                </div>
            </div>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </fieldset>
    </form>
    <script type="text/javascript">
        function addRichTextEditBlogBody() {
            richArea = new nicEditor({fullPanel : true, iconsPath : '../oip-additions/oip-assets/oip-js/nicEditorIcons.gif' }).panelInstance('ca8e6eb7-e292-4a3c-bed7-1632b43051df_Body');
        }
        bkLib.onDomLoaded(function() { addRichTextEditBlogBody(); });
    </script>
</div>
</div>
<div class="tab-pane" id="tab-images">
    <!-- ========== Begin: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-imagegroups-choose-current.txt ========== -->
    <!-- oip-module-imagegroup-choose-current.txt -->
    <div id="identity" class="span12" style="margin-top:10px;min-height:300px">
        <form id="" method="post" class="form-horizontal ">
            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
            <!-- THEBALL-CONTEXT-DYNAMICROOT-BEGIN:AaltoGlobalImpact.OIP.ImageGroupContainer:ImageGroups -->

            <fieldset id="current-imagegroups">
                <div class="control-group">
                    <label class="control-label">List of image groups</label>

                    <div id="SelectedImageGroups_d3e29c59-d572-43e4-bf05-bd0bb213d998" class="controls">

                        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroups -->


                        <div class="well tab-well">
                            <label class="checkbox">
                                <input type="checkbox" id="51cf81aa-4398-4264-8207-6663327f3e35_Selected"><a data-toggle="modal" href="#view-imagegroup" class="noteditable">Test activity images Added</a>
                            </label>
                            <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.ImageGroup_51cf81aa-4398-4264-8207-6663327f3e35_DefaultView.phtml'>Edit: Test activity images Added</a>
                        </div>


                        <!-- THEBALL-CONTEXT-END:ImageGroups -->

                        <div class="well tab-well">
                            <label class="checkbox">
                                <input type="checkbox" id="7a8d3e3d-9a85-4035-8b78-94db693953ad_Selected"><a data-toggle="modal" href="#view-imagegroup" class="noteditable">Movember</a>
                            </label>
                            <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.ImageGroup_7a8d3e3d-9a85-4035-8b78-94db693953ad_DefaultView.phtml'>Edit: Movember</a>
                        </div>


                        <!-- THEBALL-CONTEXT-END:ImageGroups -->

                        <div class="well tab-well">
                            <label class="checkbox">
                                <input type="checkbox" id="80b0c569-0c1a-4841-b53a-778e18a5942c_Selected"><a data-toggle="modal" href="#view-imagegroup" class="noteditable">Test image group 2</a>
                            </label>
                            <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.ImageGroup_80b0c569-0c1a-4841-b53a-778e18a5942c_DefaultView.phtml'>Edit: Test image group 2</a>
                        </div>


                        <!-- THEBALL-CONTEXT-END:ImageGroups -->

                        <div class="well tab-well">
                            <label class="checkbox">
                                <input type="checkbox" id="fd94985f-75aa-4264-84bc-fa4696577525_Selected"><a data-toggle="modal" href="#view-imagegroup" class="noteditable">Jeroen's image group</a>
                            </label>
                            <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.ImageGroup_fd94985f-75aa-4264-84bc-fa4696577525_DefaultView.phtml'>Edit: Jeroen's image group</a>
                        </div>


                        <!-- THEBALL-CONTEXT-END:ImageGroups -->


                    </div>
                </div>
                <script type="text/javascript">
                    $(function () {
                        $('#SelectedImageGroups_d3e29c59-d572-43e4-bf05-bd0bb213d998 input').each(function (index) {
                            $(this).prop('checked', false);
                        });

                        $('#SelectedImageGroups_d3e29c59-d572-43e4-bf05-bd0bb213d998 input').on("click", function (event) {
                            var selected = new Array();
                            $('#SelectedImageGroups_d3e29c59-d572-43e4-bf05-bd0bb213d998 input:checked').each(function () {
                                selected.push($(this).attr('id'));
                            });

// <!-- THEBALL-CONTEXT-END:* -->
                            // Context switch here!
                            $("#1d5a86e9-534c-4896-b5d2-47c9508f8f66_SelectedIDCommaSeparated").val(selected.join(",").split("_Selected").join(""));
                            // alert($("#1d5a86e9-534c-4896-b5d2-47c9508f8f66_SelectedIDCommaSeparated").val());
                        });

                        var initializationArray = $("#1d5a86e9-534c-4896-b5d2-47c9508f8f66_SelectedIDCommaSeparated").val().split(",");
                        $.each(initializationArray, function (index, value) {
                            $("#" + value + "_Selected").prop('checked', true);
                        });

                    });
                </script>
                <input type="hidden" id="1d5a86e9-534c-4896-b5d2-47c9508f8f66_SelectedIDCommaSeparated" name="1d5a86e9-534c-4896-b5d2-47c9508f8f66_SelectedIDCommaSeparated" value="7a8d3e3d-9a85-4035-8b78-94db693953ad">
                <input type="hidden" id="1d5a86e9-534c-4896-b5d2-47c9508f8f66_IsCollectionFiltered" name="1d5a86e9-534c-4896-b5d2-47c9508f8f66_IsCollectionFiltered" value="true">
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <a href="#add-imagegroup" role="button" class="btn" data-toggle="modal">Add Image Group</a>
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>

    <!-- modals -->
    <div id="view-imagegroup" class="modal hide fade well">
        <div class="modal-header">
            <button class="close" data-dismiss="modal">&times;</button>
            <h3>
                View this image group
            </h3>
        </div>
        <div class="modal-body well">
            <form method="post" class="form-horizontal">
                <!-- THEBALL-FORM-HIDDEN-FIELDS -->
                <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
                <fieldset>
                    <p>
                        Here is going to be the image group view
                    </p>
                    <div class="modal-footer">
                        <div class="control-group controls">
                            <div class="form-actions" style="padding:0;margin:0;border-top:0">
                                <button class="btn">Close window</button>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

    <div id="add-imagegroup" class="modal hide fade">
        <div class="modal-header">
            <button class="close" data-dismiss="modal">&times;</button>
            <h2 class="title">
                Add an image group
            </h2>
        </div>
        <div class="modal-body">
            <form method="post" class="form-horizontal">

                <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddImageGroupInfo:AddImageGroup -->

                <!-- THEBALL-FORM-HIDDEN-FIELDS -->
                <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddImageGroup" />
                <fieldset>
                    <div class="control-group">
                        <label class="control-label" for="737dcb27-6e73-4181-8e1d-c65b172c5008_ImageGroupTitle">Image group title</label>
                        <div class="controls">
                            <input name="737dcb27-6e73-4181-8e1d-c65b172c5008_ImageGroupTitle" class="span4" id="737dcb27-6e73-4181-8e1d-c65b172c5008_ImageGroupTitle" type="text" value="">
                        </div>
                    </div>
                    <div class="control-group controls">
                        <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                            <button value="true" name="btnCancel" class="btn">Cancel</button>
                            <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                        </div>
                    </div>

                </fieldset>

                <!-- THEBALL-CONTEXT-END:* -->
            </form>
        </div>
    </div>


    <!-- end modals -->
    <!-- end oip-module-imagegroup-choose-current.txt -->

    <!-- ========== End: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-imagegroups-choose-current.txt ========== -->
</div>
<div class="tab-pane" id="tab-locations-current">
<!-- ========== Begin: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-locations-choose-current.txt ========== -->
<!--oip-module-locations-choose-current.txt-->
<div id="identity" class="span11" style="margin-top:10px;min-height:300px">
    <form id="" method="post" class="form-horizontal ">
        <!-- THEBALL-FORM-HIDDEN-FIELDS -->
        <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
        <!-- THEBALL-CONTEXT-DYNAMICROOT-BEGIN:AaltoGlobalImpact.OIP.LocationContainer:Locations -->

        <fieldset id="current-locations">
            <div class="control-group">
                <label class="control-label">List of locations used</label>
                <div id="SelectedLocations_12956f4b-4a39-4db3-89ac-1e1ab3ddd6a3" class="controls">

                    <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:Locations -->


                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="17fe4c98-b55d-40dd-9b19-f0ca30578083_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Rahim's home</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_17fe4c98-b55d-40dd-9b19-f0ca30578083_DefaultView.phtml'>Edit Location: Rahim's home</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="4ab5177b-d3a3-4196-a595-0227bad92b46_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">India Gujarat</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_4ab5177b-d3a3-4196-a595-0227bad92b46_DefaultView.phtml'>Edit Location: India Gujarat</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="54f6d9ba-8e2a-455e-85ef-fb618b0cf25c_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Nairobi, Kenya</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_54f6d9ba-8e2a-455e-85ef-fb618b0cf25c_DefaultView.phtml'>Edit Location: Nairobi, Kenya</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="bb4607ee-113d-498d-9377-5022fca55aa7_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">New</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_bb4607ee-113d-498d-9377-5022fca55aa7_DefaultView.phtml'>Edit Location: New</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="dd2e432f-7f17-4827-94ae-36dfd176933b_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Aalto 2</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_dd2e432f-7f17-4827-94ae-36dfd176933b_DefaultView.phtml'>Edit Location: Aalto 2</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="0adcef7a-d9f6-404a-9cc5-c90d8570da2b_Selected"><a data-toggle="modal" href="#view-location" class="noteditable"></a>
                        </label>
                        <a class='remoteurlmodal' data-url=''>Edit Location: </a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="e92c3ecb-2ccb-4985-916d-8be0da8d1296_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Kamppi X - 15.11. 11:59</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_e92c3ecb-2ccb-4985-916d-8be0da8d1296_DefaultView.phtml'>Edit Location: Kamppi X - 15.11. 11:59</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->

                    <div class="well tab-well">
                        <label class="checkbox">
                            <input type="checkbox" id="fcdde612-2ee5-4572-b418-0b044291f695_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Kalle's new location 5.12.-12</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.AddressAndLocation_fcdde612-2ee5-4572-b418-0b044291f695_DefaultView.phtml'>Edit Location: Kalle's new location 5.12.-12</a>
                    </div>


                    <!-- THEBALL-CONTEXT-END:Locations -->


                </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $('#SelectedLocations_12956f4b-4a39-4db3-89ac-1e1ab3ddd6a3 input').each(function (index) {
                        $(this).prop('checked', false);
                    });

                    $('#SelectedLocations_12956f4b-4a39-4db3-89ac-1e1ab3ddd6a3 input').on("click", function (event) {
                        var selected = new Array();
                        $('#SelectedLocations_12956f4b-4a39-4db3-89ac-1e1ab3ddd6a3 input:checked').each(function () {
                            selected.push($(this).attr('id'));
                        });

// <!-- THEBALL-CONTEXT-END:* -->
                        // Context switch here!
                        $("#3b3ef480-e46d-4df5-b85a-9e363699c3f5_SelectedIDCommaSeparated").val(selected.join(",").split("_Selected").join(""));
                        // alert($("#3b3ef480-e46d-4df5-b85a-9e363699c3f5_SelectedIDCommaSeparated").val());
                    });

                    var initializationArray = $("#3b3ef480-e46d-4df5-b85a-9e363699c3f5_SelectedIDCommaSeparated").val().split(",");
                    $.each(initializationArray, function (index, value) {
                        $("#" + value + "_Selected").prop('checked', true);
                    });

                });
            </script>
            <input type="hidden" id="3b3ef480-e46d-4df5-b85a-9e363699c3f5_SelectedIDCommaSeparated" name="3b3ef480-e46d-4df5-b85a-9e363699c3f5_SelectedIDCommaSeparated" value="">
            <input type="hidden" id="3b3ef480-e46d-4df5-b85a-9e363699c3f5_IsCollectionFiltered" name="3b3ef480-e46d-4df5-b85a-9e363699c3f5_IsCollectionFiltered" value="true">
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <a href="#add-location" role="button" class="btn" data-toggle="modal">Add Location</a>
                </div>
            </div>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>

<!-- modals -->
<div id="view-location" class="modal hide fade well">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h3>
            view this location
        </h3>
    </div>
    <div class="modal-body well">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
            <fieldset>
                <p>
                    Here is going to be a map
                </p>
                <div class="modal-footer">
                    <div class="control-group controls">
                        <div class="form-actions" style="padding:0;margin:0;border-top:0">
                            <button class="btn">Close window</button>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<div id="add-location" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Add a location
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">

            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddAddressAndLocationInfo:AddLocation -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddLocation" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="48b7dfb5-6d00-430b-ada1-0b54fbf75203_LocationName">Location name</label>
                    <div class="controls">
                        <input name="48b7dfb5-6d00-430b-ada1-0b54fbf75203_LocationName" class="span4" id="48b7dfb5-6d00-430b-ada1-0b54fbf75203_LocationName" type="text" value="">
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>


<!-- end modals -->
<!-- end oip-module-locations-choose-current.txt -->

<!-- ========== End: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-locations-choose-current.txt ========== -->
</div>
<div class="tab-pane" id="tab-category">
    <!-- ========== Begin: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-categories-choose-current.txt ========== -->
    <!--oip-module-categories-choose-current.txt-->
    <div id="identity" class="span11" style="margin-top:10px;min-height:300px">
        <form id="" method="post" class="form-horizontal ">
            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
            <!-- THEBALL-CONTEXT-DYNAMICROOT-BEGIN:AaltoGlobalImpact.OIP.CategoryContainer:Categories -->

            <fieldset id="current-categories">
                <div class="control-group">
                    <label class="control-label">List of categories used</label>
                    <div id="SelectedCategories_af7475d4-5511-43a6-b33f-52a877f6d3d7" class="controls">

                        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:Categories -->


                        <label class="checkbox">
                            <input type="checkbox" id="4aca964b-6ce1-486b-a055-829e663552ef_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Aalto Global Impact</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.Category_4aca964b-6ce1-486b-a055-829e663552ef_DefaultView.phtml'>Edit Category: Aalto Global Impact</a>



                        <!-- THEBALL-CONTEXT-END:Categories -->

                        <label class="checkbox">
                            <input type="checkbox" id="669543c7-5662-4564-be67-25019f0cc5a0_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Weconomy</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.Category_669543c7-5662-4564-be67-25019f0cc5a0_DefaultView.phtml'>Edit Category: Weconomy</a>



                        <!-- THEBALL-CONTEXT-END:Categories -->

                        <label class="checkbox">
                            <input type="checkbox" id="84372e20-aadd-4403-8db0-e11a194febac_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Kalle's test category 3</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.Category_84372e20-aadd-4403-8db0-e11a194febac_DefaultView.phtml'>Edit Category: Kalle's test category 3</a>



                        <!-- THEBALL-CONTEXT-END:Categories -->

                        <label class="checkbox">
                            <input type="checkbox" id="c31e7181-a784-4dc7-8a7e-563882d8c981_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Events</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.Category_c31e7181-a784-4dc7-8a7e-563882d8c981_DefaultView.phtml'>Edit Category: Events</a>



                        <!-- THEBALL-CONTEXT-END:Categories -->

                        <label class="checkbox">
                            <input type="checkbox" id="da9f373f-a78b-49cf-85d6-284699a21a68_Selected"><a data-toggle="modal" href="#view-location" class="noteditable">Kalle's test category 2</a>
                        </label>
                        <a class='remoteurlmodal' data-url='AaltoGlobalImpact.OIP.Category_da9f373f-a78b-49cf-85d6-284699a21a68_DefaultView.phtml'>Edit Category: Kalle's test category 2</a>



                        <!-- THEBALL-CONTEXT-END:Categories -->


                    </div>
                </div>
                <script type="text/javascript">
                    $(function () {
                        $('#SelectedCategories_af7475d4-5511-43a6-b33f-52a877f6d3d7 input').each(function (index) {
                            $(this).prop('checked', false);
                        });

                        $('#SelectedCategories_af7475d4-5511-43a6-b33f-52a877f6d3d7 input').on("click", function (event) {
                            var selected = new Array();
                            $('#SelectedCategories_af7475d4-5511-43a6-b33f-52a877f6d3d7 input:checked').each(function () {
                                selected.push($(this).attr('id'));
                            });

// <!-- THEBALL-CONTEXT-END:* -->
                            // Context switch here!
                            $("#7d7f17e3-580b-4705-b792-0ea4a06626ba_SelectedIDCommaSeparated").val(selected.join(",").split("_Selected").join(""));
                            // alert($("#7d7f17e3-580b-4705-b792-0ea4a06626ba_SelectedIDCommaSeparated").val());
                        });

                        var initializationArray = $("#7d7f17e3-580b-4705-b792-0ea4a06626ba_SelectedIDCommaSeparated").val().split(",");
                        $.each(initializationArray, function (index, value) {
                            $("#" + value + "_Selected").prop('checked', true);
                        });

                    });
                </script>
                <input type="hidden" id="7d7f17e3-580b-4705-b792-0ea4a06626ba_SelectedIDCommaSeparated" name="7d7f17e3-580b-4705-b792-0ea4a06626ba_SelectedIDCommaSeparated" value="84372e20-aadd-4403-8db0-e11a194febac">
                <input type="hidden" id="7d7f17e3-580b-4705-b792-0ea4a06626ba_IsCollectionFiltered" name="7d7f17e3-580b-4705-b792-0ea4a06626ba_IsCollectionFiltered" value="true">
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <a href="#add-category" role="button" class="btn" data-toggle="modal">Add Category</a>
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>

    <!-- modals -->
    <div id="add-category" class="modal hide fade">
        <div class="modal-header">
            <button class="close" data-dismiss="modal">&times;</button>
            <h2 class="title">
                Add a category
            </h2>
        </div>
        <div class="modal-body">
            <form method="post" class="form-horizontal">

                <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddCategoryInfo:AddCategory -->

                <!-- THEBALL-FORM-HIDDEN-FIELDS -->
                <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddCategory" />
                <fieldset>
                    <div class="control-group">
                        <label class="control-label" for="7fdeed75-2c27-4c5e-8cc5-e60a1ebfe92d_CategoryName">Category name</label>
                        <div class="controls">
                            <input name="7fdeed75-2c27-4c5e-8cc5-e60a1ebfe92d_CategoryName" class="span11" id="7fdeed75-2c27-4c5e-8cc5-e60a1ebfe92d_CategoryName" type="text" value="">
                        </div>
                    </div>
                    <div class="control-group controls">
                        <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                            <button value="true" name="btnCancel" class="btn">Cancel</button>
                            <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                        </div>
                    </div>

                </fieldset>

                <!-- THEBALL-CONTEXT-END:* -->
            </form>
        </div>
    </div>


    <!-- end modals -->
    <!-- end oip-module-categories-choose-current.txt -->

    <!-- ========== End: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-categories-choose-current.txt ========== -->
</div>
<div class="tab-pane" id="tab-delete">
    <!-- ========== Begin: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-blog-delete.txt ========== -->
    <!-- oip-module-activities-delete.txt -->
    <div id="identity" class="span7" style="margin-top:10px">
        <form id="" method="post" class="form-horizontal ">
            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
            <fieldset id="">
                Are you sure you want to delete this blog post? All the permanent links pointing to this blog will break.
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color: transparent">
                        <button value="true" name="btnCancel"  class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary btn-danger" name="RootSourceAction" id="RootSourceAction" value="Delete">Delete</button>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
    <!-- end oip-module-activities-delete.txt -->

    <!-- ========== End: oip-group\..\oip-containers\..\oip-modules\../oip-modules/oip-module-blog-delete.txt ========== -->
</div>
</div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->

</div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.BlogContainer -->

</section>
</div>
<footer class="footer">
    <div class="container"><div class="span12">
        <p class="pull-right"><a href="#">Back to top</a></p>
    </div>
        <div class="span4">
            <ul class="aalto-footer">
                <li >
                    <a href="http://www.aalto.fi/en">Aalto.fi</a>
                    <ul>
                        <li class="taik"><a href="http://arts.aalto.fi/en/">School of Arts, Design and Architecture</a></li>
                        <li class="hse"><a href="http://business.aalto.fi/en/">School of Business</a></li>
                        <li class="chem"><a href="http://chem.aalto.fi/en/">School of Chemical Technology</a></li>
                        <li class="elec"><a href="http://elec.aalto.fi/en/">School of Electrical Engineering</a></li>
                        <li class="eng"><a href="http://eng.aalto.fi/en/">School of Engineering</a></li>
                        <li class="sci"><a href="http://sci.aalto.fi/en/" style="border: none;">School of Science</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="span4">
            <p>Aalto Global Impact has been formed to bring together these existing parties working in societal issues and to help them develop their activities further</p>
        </div>
        <div class="span3">
            <p>The <a id="edittoggle">Open</a> Innovation Platform is offered to you by Aalto Global Impact, and Aalto University organisation</p>
            <p>All content licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
            <p>Icons from <a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        </div>
    </div>
</footer>


<!-- ========== Begin: oip-group\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->
<!-- oip-modal-collection.txt -->

<!-- ========== Begin: oip-group\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->
<!-- oip-modal-header.txt -->
<div class="modal hide fade well in-context-edit" id="IncontextEditDialog_Text_Short">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="InContextEditFieldID" name="InContextEditFieldID" type="hidden" value="NotSet" />
            <input id="RootSourceAction" name="RootSourceAction" type="hidden" value="Save" />
            <input class="span4" type="text" name="Text_Short" id="Text_Short" value="" />
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-header.txt -->

<!-- ========== End: oip-group\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->


<!-- ========== Begin: oip-group\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->
<!-- oip-modal-text-long.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_Text_Long">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="InContextEditFieldID" name="InContextEditFieldID" type="hidden" value="NotSet" />
            <input id="RootSourceAction" name="RootSourceAction" type="hidden" value="Save" />
            <textarea class="span5" rows="30" id="Text_Long" name="Text_Long"></textarea>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </div>
    </form>
    <script type="text/javascript">
        function addRichTextEditTextLong() {
            richArea = new nicEditor({fullPanel : true, iconsPath : '../oip-additions/oip-assets/oip-js/nicEditorIcons.gif' }).panelInstance('Text_Long');
        }
        // Moved to actual dialog initiation script as the content weren't appearing from previous data
        // bkLib.onDomLoaded(function() { addRichTextEditTextLong(); });
    </script>
</div>
<!-- end oip-modal-text-long.txt -->

<!-- ========== End: oip-group\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->


<!-- ========== Begin: oip-group\..\oip-containers\..\oip-modals\oip-modal-radiogroup.txt ========== -->
<!-- oip-modal-radiogroup.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_RadioGroup">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
        <div class="modal-body">
            <div class="control-group">
                <label class="checkbox">
                    <input type="radio" id="LocationName" name="_LocationName" value="_LocationName">LocationName</label>
            </div>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-radiogroup.txt -->

<!-- ========== End: oip-group\..\oip-containers\..\oip-modals\oip-modal-radiogroup.txt ========== -->


<!-- ========== Begin: oip-group\..\oip-containers\..\oip-modals\oip-modal-multiselect.txt ========== -->
<!-- oip-modal-multiselect.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_MultiSelect">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <div class="control-group">
                <label class="control-label" for="multiSelect"> Assign category </label>
                <div class="controls">
                    <select multiple="multiple" id="multiSelect" size="12">
                        <optgroup label="Projects">
                            <option> Projects </option>
                            <option selected="selected"> Finland </option>
                            <option> South America </option>
                            <option> Africa </option>
                        </optgroup> <optgroup label="Events">
                        <option selected="selected"> Events </option>
                        <option> Seminar </option>
                        <option selected="selected"> Conference </option>
                        <option> Meeting </option>
                    </optgroup> <optgroup label="Courses">
                        <option> Courses </option>
                        <option> Ba </option>
                        <option> MA </option>
                        <option> Design </option>
                    </optgroup> <optgroup label="Research">
                        <option> Research </option>
                        <option> BoP </option>
                        <option selected="selected"> Inclusive Business </option>
                    </optgroup>
                    </select>
                </div>
            </div>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-multiselect.txt -->

<!-- ========== End: oip-group\..\oip-containers\..\oip-modals\oip-modal-multiselect.txt ========== -->

<div class="modal hide fade well in-context-edit" id="IDAction_ConfirmRemove">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <input id="RootSourceAction" name="RootSourceAction" type="hidden" value="" />
            <p name="question" id="question">Not set</p>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color: transparent">
                    <button value="true" name="btnCancel"  class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-danger" name="RootSourceAction" id="RootSourceAction" value="Delete">Delete</button>
                </div>
            </div>

        </div>
    </form>
</div>

<div class="modal hide fade well" id="IDRemoteUrlModal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <div id="IDRemoteUrlModalBody">
        Loading content...
    </div>
</div>

<!-- end oip-modal-collection.txt -->
<!-- ========== End: oip-group\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->



<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-transition.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-alert.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-modal.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-dropdown.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-scrollspy.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tab.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tooltip.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-popover.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-button.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-collapse.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-carousel.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-typeahead.js"></script>
<!-- calendar -->
<script src="../oip-additions/oip-assets/oip-js/third-party-calendar.js"></script>
<!-- OIP specific -->
<script src="../oip-additions/oip-assets/oip-js/in-context-editing.js"></script>
<script src="../oip-additions/oip-assets/oip-js/modal-id-actions.js"></script>
</body>
</html>

