<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head-admin.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-public/oip-container-navbar-public-admin.txt' ?>
<div class="container">
    <section id="container-focus" class="container well" >
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    </section>
    <section class="container well">
        <?php include '../oip-containers/test-oip-container-blog-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/test-oip-public-container-groups-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupSummaryContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/test-oip-public-container-activities-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/test-oip-public-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/test-oip-container-latest-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
    </section>
</div>
        <?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
