<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head-map.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../www-public/oip-container-navbar-www-public.txt' ?>
<div class="container">
    <section id="container-focus" class="well">
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    <div class="span2 map-result-list">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
        </section>
</div>
<div class="container masonry">
    <div class="row-fluid">
        <div class="filter-box">
            <button type="button" class="btn btn-filter" data-toggle="collapse" data-target=".isotope-sort">Filter</button>
            <ul class="isotope-sort" style="padding:10px">
                <li class="isotope-sort-title">Filter:</li>
                <li class="isotope-sort-item"><a href="#" class="active" data-filter="*">All</a></li>
                <li class="isotope-sort-item"><a href="#"  class="" data-filter=".blogs">Blogs</a></li>
                <li class="isotope-sort-item"><a href="#"  class="" data-filter=".groups">Groups</a></li>
                <li class="isotope-sort-item"><a href="#"  class="" data-filter=".activities">Activities</a></li>
                <li class="isotope-sort-item"><a href="#"  class="" data-filter=".other">Other</a></li>
            </ul>
        </div>

        <ul class="gallery four_col" style="padding: 10px"><!-- three_col four_col two_col -->
            <li class="blogs"">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Project 01—Test on 26.02.2013 on Dynamic content 05</a></h4>
                    <p>Praesent sodales, lorem in laoreet elementum, enim mi eleifend felis, ut adipiscing eros sem a ante. Aenean ullamcorper congue lorem, eu sollicitudin diam iaculis ut. Sed erat nisi, pulvinar et vestib...</p>
                    <div class="badge category"><a href="#">Perhekahvila, Helsinki, MLL</a>, <a href="#">muut</a></div>
                    <span class="credit"><a href="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" target="_blank">CC BY 2.0  Jeremy Keith</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="groups">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Perhekahvila Tampere</a></h4>
                    <div class="badge category"><a href="#">Perhekahvila, Tampere, MLL</a>, <a href="#">lastenhoitoapua</a></div>
                    <span class="credit"><a href="../caloom-additions/caloom-images/map-images/map1_03.png" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a href="portfolio-video.html" class="hover"><img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="The Meth Minute 39" /><span class="videoicon"></span><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-video.html">Vanhempainnetti Lauttasaari</a></h4>
                    <p>Optional text. Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...</p>
                    <div class="badge category"><a href="#">vanhempainnetti, MLL</a></div>
                </div><!--close entry-summary-->
            </li>
            <li class="groups">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Tampere</a></h4>
                    <p>Just a filler image to make 16 images</p>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Tampere, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525755090/in/photostream/" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>

            <li class="blogs">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Harrastuskerhot Helsinki</a></h4>
                    <div class="badge category"><a href="#">Harrastuskerhot, Helsinki, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4867174108/" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">perhekahvila Lauttasaari</a></h4>
                    <div class="badge category"><a href="#">Perhekahvila, Lauttasaari, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525123431/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Lauttasaari</a></h4>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Lauttasaari, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4703289770/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="blogs">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Helsinki</a></h4>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Helsinki, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525754738/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="blogs">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Project 01—Test on 26.02.2013 on Dynamic content 05</a></h4>
                    <p>Praesent sodales, lorem in laoreet elementum, enim mi eleifend felis, ut adipiscing eros sem a ante. Aenean ullamcorper congue lorem, eu sollicitudin diam iaculis ut. Sed erat nisi, pulvinar et vestib...</p>
                    <div class="badge category"><a href="#">Perhekahvila, Helsinki, MLL</a>, <a href="#">muut</a></div>
                    <span class="credit"><a href="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" target="_blank">CC BY 2.0  Jeremy Keith</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="groups">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Perhekahvila Tampere</a></h4>
                    <div class="badge category"><a href="#">Perhekahvila, Tampere, MLL</a>, <a href="#">lastenhoitoapua</a></div>
                    <span class="credit"><a href="../caloom-additions/caloom-images/map-images/map1_03.png" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a href="portfolio-video.html" class="hover"><img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="The Meth Minute 39" /><span class="videoicon"></span><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-video.html">Vanhempainnetti Lauttasaari</a></h4>
                    <p>Optional text. Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...</p>
                    <div class="badge category"><a href="#">vanhempainnetti, MLL</a></div>
                </div><!--close entry-summary-->
            </li>
            <li class="groups">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Tampere</a></h4>
                    <p>Just a filler image to make 16 images</p>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Tampere, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525755090/in/photostream/" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>

            <li class="blogs">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Harrastuskerhot Helsinki</a></h4>
                    <div class="badge category"><a href="#">Harrastuskerhot, Helsinki, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4867174108/" target="_blank">CC BY 2.0 FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">perhekahvila Lauttasaari</a></h4>
                    <div class="badge category"><a href="#">Perhekahvila, Lauttasaari, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525123431/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="activities">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Lauttasaari</a></h4>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Lauttasaari, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4703289770/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
            <li class="blogs">
                <a class="hover" href="portfolio-single.html">
                    <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
                <div class="entry-summary">
                    <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Helsinki</a></h4>
                    <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Helsinki, MLL</a></div>
                    <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525754738/" target="_blank">CC BY 2.0  FontFont</a></span>
                </div><!--close entry-summary-->
            </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Project 01—Test on 26.02.2013 on Dynamic content 05</a></h4>
                <p>Praesent sodales, lorem in laoreet elementum, enim mi eleifend felis, ut adipiscing eros sem a ante. Aenean ullamcorper congue lorem, eu sollicitudin diam iaculis ut. Sed erat nisi, pulvinar et vestib...</p>
                <div class="badge category"><a href="#">Perhekahvila, Helsinki, MLL</a>, <a href="#">muut</a></div>
                <span class="credit"><a href="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" target="_blank">CC BY 2.0  Jeremy Keith</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Perhekahvila Tampere</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Tampere, MLL</a>, <a href="#">lastenhoitoapua</a></div>
                <span class="credit"><a href="../caloom-additions/caloom-images/map-images/map1_03.png" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a href="portfolio-video.html" class="hover"><img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="The Meth Minute 39" /><span class="videoicon"></span><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-video.html">Vanhempainnetti Lauttasaari</a></h4>
                <p>Optional text. Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...</p>
                <div class="badge category"><a href="#">vanhempainnetti, MLL</a></div>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Tampere</a></h4>
                <p>Just a filler image to make 16 images</p>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Tampere, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525755090/in/photostream/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>

        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Harrastuskerhot Helsinki</a></h4>
                <div class="badge category"><a href="#">Harrastuskerhot, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4867174108/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">perhekahvila Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525123431/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4703289770/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Helsinki</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525754738/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Project 01—Test on 26.02.2013 on Dynamic content 05</a></h4>
                <p>Praesent sodales, lorem in laoreet elementum, enim mi eleifend felis, ut adipiscing eros sem a ante. Aenean ullamcorper congue lorem, eu sollicitudin diam iaculis ut. Sed erat nisi, pulvinar et vestib...</p>
                <div class="badge category"><a href="#">Perhekahvila, Helsinki, MLL</a>, <a href="#">muut</a></div>
                <span class="credit"><a href="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" target="_blank">CC BY 2.0  Jeremy Keith</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Perhekahvila Tampere</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Tampere, MLL</a>, <a href="#">lastenhoitoapua</a></div>
                <span class="credit"><a href="../caloom-additions/caloom-images/map-images/map1_03.png" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a href="portfolio-video.html" class="hover"><img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="The Meth Minute 39" /><span class="videoicon"></span><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-video.html">Vanhempainnetti Lauttasaari</a></h4>
                <p>Optional text. Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...</p>
                <div class="badge category"><a href="#">vanhempainnetti, MLL</a></div>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Tampere</a></h4>
                <p>Just a filler image to make 16 images</p>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Tampere, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525755090/in/photostream/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>

        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Harrastuskerhot Helsinki</a></h4>
                <div class="badge category"><a href="#">Harrastuskerhot, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4867174108/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">perhekahvila Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525123431/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4703289770/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Helsinki</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525754738/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Project 01—Test on 26.02.2013 on Dynamic content 05</a></h4>
                <p>Praesent sodales, lorem in laoreet elementum, enim mi eleifend felis, ut adipiscing eros sem a ante. Aenean ullamcorper congue lorem, eu sollicitudin diam iaculis ut. Sed erat nisi, pulvinar et vestib...</p>
                <div class="badge category"><a href="#">Perhekahvila, Helsinki, MLL</a>, <a href="#">muut</a></div>
                <span class="credit"><a href="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" target="_blank">CC BY 2.0  Jeremy Keith</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Perhekahvila Tampere</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Tampere, MLL</a>, <a href="#">lastenhoitoapua</a></div>
                <span class="credit"><a href="../caloom-additions/caloom-images/map-images/map1_03.png" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a href="portfolio-video.html" class="hover"><img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="The Meth Minute 39" /><span class="videoicon"></span><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-video.html">Vanhempainnetti Lauttasaari</a></h4>
                <p>Optional text. Wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat...</p>
                <div class="badge category"><a href="#">vanhempainnetti, MLL</a></div>
            </div><!--close entry-summary-->
        </li>
        <li class="groups">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-tre.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Tampere</a></h4>
                <p>Just a filler image to make 16 images</p>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Tampere, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525755090/in/photostream/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>

        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Harrastuskerhot Helsinki</a></h4>
                <div class="badge category"><a href="#">Harrastuskerhot, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4867174108/" target="_blank">CC BY 2.0 FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">perhekahvila Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Perhekahvila, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525123431/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="activities">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-lauttasaari.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Lauttasaari</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Lauttasaari, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4703289770/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        <li class="blogs">
            <a class="hover" href="portfolio-single.html">
                <img src="../caloom-2013/caloom-2013-additions/images/placeholder/stamen-subdued-tones-hki-center.png" alt="" /><span class="plus"></span></a>
            <div class="entry-summary">
                <h4><a href="portfolio-single.html">Tapahtumat, retket ja leirit Helsinki</a></h4>
                <div class="badge category"><a href="#">Tapahtumat, Retket, Leirit, Helsinki, MLL</a></div>
                <span class="credit"><a href="http://www.flickr.com/photos/fontfont/4525754738/" target="_blank">CC BY 2.0  FontFont</a></span>
            </div><!--close entry-summary-->
        </li>
        </ul>
    </div>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>

<!-- scripts on this page ================ -->

<script src='../oip-additions/oip-assets/oip-js/jquery.isotope.min.js'></script><!--filter and masonry script-->
<script src='../oip-additions/oip-assets/oip-js/jquery.isotope.init.js'></script><!--custom settings-->


</body>
</html>
