<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar-public.txt' ?>
<div class="container">
	<section id="container-focus" class="container well" >
<?php include '../oip-containers/oip-public-container-activities-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer -->
	</section>
	<section class="container well">
<?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
	</section>	
		<section class="container well">
<?php include '../oip-containers/oip-container-footer.txt' ?>
	</section>
</div>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
