<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar-public.txt' ?>
<div class="container" style="margin-left: 0px;margin-right: 0px; width:100%;position:relative">
    <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    <div class="span2 bs-docs-sidebar" style="position: absolute; top: 8px;right: 8px;height: 504px;">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
</div>
<div class="container">
    <section class="container well">
        <?php include '../oip-containers/oip-container-blog-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-public-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-public-container-groups-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupSummaryContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-public-container-activities-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer  -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
