<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar.txt' ?>
<div class="container">
    <section id="container-focus" class="container well" >
        <?php include '../oip-containers/oip-container-activity-single-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivityContainer -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>

