<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar.txt' ?>
<div class="container">
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer--> <!-- rename this to MapContainerSummary ? -->
    <div class="span2 map-result-list">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>

