<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body class="in-context-edit" data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include '../oip-containers/oip-container-navbar-in-context-edit.txt' ?>
<div class="container">
    <section id="container-focus" class="container well" >
        <?php include '../oip-containers/oip-container-activities-in-context-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>

