<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar.txt' ?>
<div class="container" style="margin-left: 0px;margin-right: 0px; width:100%;position:relative">
        <?php include '../oip-containers/test-oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer--> <!-- rename this to MapContainerSummary ? -->
    <div class="span2 bs-docs-sidebar" style="position: absolute; top: 8px;right: 8px;height: 504px; background-color:rgba(33, 32, 31, 0.8);
-webkit-border-radius: 6px;
-moz-border-radius: 6px;
border-radius: 6px;
-webkit-box-shadow: 0 1px 4px rgba(0,0,0,.065);
-moz-box-shadow: 0 1px 4px rgba(0,0,0,.065);
box-shadow: 0 1px 4px rgba(0,0,0,.065);
">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>

