<!DOCTYPE html>
<html lang="en">


<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">


<!-- default-navbar-fixed-top.txt -->
<?php include '../default-modules/default-navbar-fixed-top.txt' ?><!-- default-navbar-fixed-top.txt -->

<!--the container class sets the width of the container and centers it -->

<!-- section -->
<section id="gridSystem">

<div class="container-fluid">	
	
<div class="tabbable">

<ul class="nav nav-pills">
<li class="active" style="padding-right:10px">
	<a href="#map1" data-toggle="tab">My Map #1
		<span class="badge padaround" style="margin-left:20px">2</span>
		<span class="badge badge-important padaround">3</span>
</a>
</li>

<li style="padding-right:10px">
	<a href="#map2" data-toggle="tab">My Map #2
	<span class="badge padaround" style="margin-left:20px">2</span>
	<span class="badge badge-important padaround">3</span>
</a>
</li>

<li style="padding-right:10px">
	<a href="#map3" data-toggle="tab">My Map #3
	<span class="badge padaround" style="margin-left:20px">2</span>
	<span class="badge badge-important padaround">3</span>
</a>
</li>

<li style="padding-right:10px">
	<a href="#map4" data-toggle="tab">My Map #4
	<span class="badge padaround" style="margin-left:20px">2</span>
	<span class="badge badge-important padaround">3</span>
</a>
</li>

<li style="padding-right:10px">
	<a href="#map5" data-toggle="tab">My Map #5
	<span class="badge padaround" style="margin-left:20px">2</span>
	<span class="badge badge-important padaround">3</span>
</a>
</li>

</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="map1">
				<?php include '../default-modules/default-my-map-item1.txt' ?>
			</div>
			<div class="tab-pane" id="map2">
				<?php include '../default-modules/default-my-map-item2.txt' ?>
			</div>
			<div class="tab-pane" id="map3">
				<?php include '../default-modules/default-my-map-item3.txt' ?>
			</div>
			<div class="tab-pane" id="map4">
				<?php include '../default-modules/default-my-map-item4.txt' ?>
			</div>
			<div class="tab-pane" id="map5">
				<?php include '../default-modules/default-my-map-item5.txt' ?>
			</div>
</div><!--end of tab-content-->
</div><!--end of tabbable -->
</div><!--End of Container Fluid-->

<div class="container">
<!-- explanation -->
<div>
	<?php include '../default-modules/default-explanation.txt' ?>
</div>

<hr class="soften">

<div>
<?php include '../default-modules/default-blog.txt' ?>
</div>

</section><!-- section -->

<!-- default-footer.txt -->
<div class="container">
<?php include'default-account.txt' ?><!--default-account.txt-->	
	
<?php include'default-footer.txt' ?><!-- default-footer.txt-->
</div>

</div><!-- /container -->

<!--Modals-->
<?php include '../default-modules/default-modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->
</div>

</body>
</html>