<!DOCTYPE html>
<html lang="en">

<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">
	
<!-- result list -->
<?php include'../default-modules/default-result-list.txt' ?>
	

<!-- default-navbar-fixed-top.txt -->
<?php include '../default-modules/default-navbar-fixed-top.txt' ?><!-- default-navbar-fixed-top.txt -->

<!--the container class sets the width of the container and centers it -->

<div class="container-fluid">
<!-- section -->
<section id="gridSystem">

<!-- Main Content -->
<div class="header">
	<!-- current map -->
	<?php include'../default-modules/default-map.txt' ?>
</div>

<!-- maps you follow -->
<div class="row-fluid">
<?php include '../default-modules/default-followed.txt' ?>
</div>

<!-- explanation -->
		<?php include '../default-modules/default-explanation.txt' ?>

</section><!-- section -->

<!-- default-footer.txt -->
<div class="row-fluid">
<?php include'default-footer.txt' ?><!-- default-footer.txt-->
</div>
</div><!-- /container -->

<!--Modals-->
<?php include '../default-modules/default-modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->
</div>
</body>
</html>