<!DOCTYPE html>
<html lang="en">
<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">

<!-- default-navbar.txt -->
<?php include'default-navbar.txt' ?><!-- default-navbar.txt -->

<!--the container class sets the width of the container and centers it -->
<div class="container">
<!-- section -->
<section id="gridSystem">
<!-- row -->
<div class="row">
<?php include'../default-modules/default-map.txt' ?>
<?php include'../default-modules/default-result-list.txt' ?>
</div><!-- row -->

<!-- followed -->
<?php include '../default-modules/default-followed.txt' ?><!-- /followed -->

<!-- explanation -->
<?php include '../default-modules/default-explanation.txt' ?><!-- /explanation -->

</section><!-- section -->

<!-- default-footer.txt -->
<?php include'default-footer.txt' ?><!-- default-footer.txt-->
</div><!-- /container -->

<!--Modals-->
<?php include '../default-modules/default-modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->

</body>
</html>