<!DOCTYPE html>
<html lang="en">


<!-- default-head.txt -->
<?php include 'default-head.txt' ?><!-- default-head.txt -->

<body data-spy="scroll" data-target=".subnav" data-offset="50">


<!-- default-navbar-fixed-top.txt -->
<?php include '../default-modules/default-navbar-fixed-top.txt' ?><!-- default-navbar-fixed-top.txt -->

<!--the container class sets the width of the container and centers it -->

<!-- section -->
<section id="gridSystem">

<div class="container-fluid">	
	
<!-- tabbable -->
<div class="tabbable">
<!-- tab list -->
<ul class="nav nav-pills">
<?php include '../default-modules/default-tab-map-item1.txt' ?>
<?php include '../default-modules/default-tab-map-item2.txt' ?>
<?php include '../default-modules/default-tab-map-item3.txt' ?>
<?php include '../default-modules/default-tab-map-item4.txt' ?>
<?php include '../default-modules/default-tab-map-item5.txt' ?>
</ul>
<!-- end tab list -->
<!-- tab content -->
<div class="tab-content">
<?php include '../default-modules/default-my-map-item1.txt' ?>
<?php include '../default-modules/default-my-map-item2.txt' ?>
<?php include '../default-modules/default-my-map-item3.txt' ?>
<?php include '../default-modules/default-my-map-item4.txt' ?>
<?php include '../default-modules/default-my-map-item5.txt' ?>
</div><!--end tabcontent-->
</div><!--end tabbable -->
</div><!--End Container Fluid-->

<div class="container">
<!-- explanation -->
<div>
	<?php include '../default-modules/default-explanation.txt' ?>
</div>

<hr class="soften">

<div>
<?php include '../default-modules/default-blog.txt' ?>
</div>

</section><!-- section -->

<!-- default-footer.txt -->
<div class="container">
<?php include'default-account.txt' ?><!--default-account.txt-->	
	
<?php include'default-footer.txt' ?><!-- default-footer.txt-->
</div>

</div><!-- /container -->

<!--Modals-->
<?php include '../default-modules/default-modals.txt' ?><!--/Modals-->

<!-- Le javascript -->
<?php include '../default-modules/default-le-javascript.txt' ?><!-- Le javascript -->
</div>

</body>
</html>