<section id="container-focus" class="container well" >
  <form method="post" class="form-horizontal">
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Category -->    
    <input id="RootSourceName" name="RootSourceName" type="hidden" value="" />
    <fieldset>
      <div class="control-group">
        <label class="control-label" for="[!ATOM]ID[ATOM!]_CategoryName">Category name</label>
        <div class="controls">
          <input name="[!ATOM]ID[ATOM!]_CategoryName" class="span11" id="[!ATOM]ID[ATOM!]_CategoryName" type="text" value="[!ATOM]CategoryName[ATOM!]" />
        </div>
      </div>
      <div class="control-group controls">
        <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
          <button value="true" name="btnCancel" class="btn">Cancel</button>
        	<input type="hidden" name="RootSourceAction" value="Save" />
          <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
        </div>
      </div>
    </fieldset>
<!-- THEBALL-CONTEXT-END:* -->  
  </form>
</section>
