<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<div class="container">
    <section id="container-focus" class="container well" >
        <?php include '../oip-modules/oip-module-location-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AddressAndLocation -->
    </section>
</div>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
