<!-- oip-layout-account-summary.phtml -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include '../oip-modules/oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar.txt' ?>
<div class="container">
    <section id="container-focus" class="container well" >
        <?php include '../oip-containers/oip-container-account-welcome.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.PersonalContainer -->
    </section>
    <section class="container well">
        <?php include '../oip-containers/oip-container-footer.txt' ?>
    </section>
</div><!-- end container -->
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-account-summary.phtml -->
