<!DOCTYPE html>
<html lang="en">
<?php include 'example1-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container-fluid marketing well" >
<?php include 'example1-container-referenceevent-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.TBReferenceEvent -->
</body>
</html>