<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include 'example1-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- section -->
<section id="gridSystem">
<!-- container -->
<div id="primary" class="container-fluid marketing well" style="margin-top:0px;background-color:white">
<?php include 'example1-container-referenceevent-edit.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.TBReferenceEvent -->
</body>
</html>