<!-- oip-layout-account-edit -->
<!DOCTYPE html>
<html lang="en">
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- Register email -->
<div class="container">
<!-- section -->
	<section id="emailcontainer"> 
<!-- container -->
	<div id="emailregistering" class="container" >
<?php include 'tbp-container-registeremail.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.TBPRegisterEmail -->
	</div>

	</section> 
<!-- end section -->
</body>
</html>
<!-- end oip-layout-account-edit.txt -->
