<!-- oip-layout-account-edit -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50" >
<!-- Register email -->
<!-- end navbar -->
<div class="container">
<!-- section -->
	<section id="emailcontainer"> 
<!-- container -->
	<div id="emailregistering" class="container" >
<?php include 'tbp-container-registeremail.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.TBPRegisterEmail -->
	</div>
<!-- end container -->
	</section> 
<!-- end section -->
</body>
</html>
<!-- end oip-layout-account-edit.txt -->
