<!-- oip-layout-collection-groups1.txt -->
<!DOCTYPE html>
<html lang="en">
<!-- head -->
<?php include '../oip-layouts/oip-head.txt' ?>
<!-- end head -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- navbar -->
<?php include '../oip-containers/oip-container-navbar.txt' ?><!-- UseInformationObjectAsRoot:NavigationContainer -->
<!-- end navbar -->
<div class="container">
<!-- section -->
<section id="">
<!-- container -->
<div id="primary" class="container marketing well" style="margin-top:0px;background-color:white">
oip-layout-collection-groups1.txt<?php include '../oip-containers/oip-container-collection-groups1.txt' ?>
</div>
<div id="summary" class="container">
oip-container-groups-secondary.txt<?php include '../oip-containers/oip-container-groups-secondary.txt' ?>
	<!-- fixed -->
	<!-- required -->
<?php include '../oip-containers/oip-container-footer.txt' ?><!--UseInformationObjectAsRoot:FooterContainer  -->
</div>
<!-- end container -->
</section>
<!-- end section -->
</div>
<!-- javascript -->
<?php include '../oip-modules/oip-le-javascript.txt' ?>
<!-- end javascript -->
</body>
</html>
<!-- end oip-layout-collection-groups1.txt -->
