<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->
<div class="header clearfix">
    <h2>
        <!-- start oip-atom-title.txt -->
        <a data-id="[!ATOM]ID[ATOM!]_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">[!ATOM]Title[ATOM!]</a>
        <!-- end oip-atom-title.txt -->
        <br>
        <p>
            <img src="[!ATOM]ProfileImage.ImageData.ContentUrlBase[ATOM!]_320x240_crop.jpg" />
        </p>
        <small>
            <!-- start oip-atom-subtitle.txt -->
            <a data-id="[!ATOM]ID[ATOM!]_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">[!ATOM]SubTitle[ATOM!]</a>
            <!-- end oip-atom-subtitle.txt -->
        </small>
    </h2>
    <div class="btn-toolbar sharing-panel clearfix">
        <div class="btn-group">
            <a class="btn" href="#"><i class="icon-facebook"></i></a>
            <a class="btn" href="#"><i class="icon-linkedin"></i></a>
            <a class="btn" href="#"><i class="icon-twitter"></i></a>
            <a class="btn" href="#"><i class="icon-envelope"></i></a>
        </div>
    </div>
    <div class="border border-news clearfix">
        <span class="label label-news">News</span>
    </div>
</div>

<div class="content">
    <div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
        <p>
            [!ATOM]Body[ATOM!]
        </p>
    </div>
</div>

<div class="media">
    <div id="flowcontainer" class="thumbnails">
        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->
        <li class="span5">
            <div class="oipimagecollection thumbnail">
                <a data-toggle="modal" href="#ImagesCollection[!ATOM]ID[ATOM!]" rel="tooltip" title="click this image to open this image large and some other images if present">
                    <img src="[!ATOM]FeaturedImage.ImageData.ContentUrlBase[ATOM!]_320x240_crop.jpg" class="thumbnail" alt="[!ATOM]Title[ATOM!]"/>
                    <br>
                    [!ATOM]Title[ATOM!]
                </a>
            </div>
        </li>
        <li class="span5">
            <div id="ImagesCollection[!ATOM]ID[ATOM!]" class="modal hide fade">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal">&times;</button>
                    <h2 class="title">[!ATOM]Title[ATOM!]</h2>
                    <p>[!ATOM]Description[ATOM!]</p>
                </div>
                <div class="modal-body">
                    <div id="#myCarousel[!ATOM]ID[ATOM!]" class="carousel">
                        <!-- Carousel items -->
                        <div class="columns">
                            <div id="myCarousel[!ATOM]ID[ATOM!]" class="carousel slide image-carousel">
                                <div class="carousel-inner">
                                    <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->
                                    <div class="item">
                                        <img src="[!ATOM]ImageData.ContentUrlBase[ATOM!]_1280x720_whole.jpg" alt="[!ATOM]Caption[ATOM!]">
                                        <div class="carousel-caption">
                                            <h4>[!ATOM]Title[ATOM!]</h4>
                                            <p>[!ATOM]Caption[ATOM!]</p>
                                        </div>
                                    </div>
                                    <!-- THEBALL-CONTEXT-END:* -->
                                </div>
                                <a class="left carousel-control" href="#myCarousel[!ATOM]ID[ATOM!]" data-slide="prev">‹</a>
                                <a class="right carousel-control" href="#myCarousel[!ATOM]ID[ATOM!]" data-slide="next">›</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <!-- end oip-module-modal-images.txt -->
        <!-- THEBALL-CONTEXT-END:ImageGroupCollection -->
    </div>
    <br>
    [!ATOM]IFrameSources[ATOM!]
    <script>
        $(function(){
            var $container = $('#flowcontainer');
            $container.isotope({
                itemSelector: '.oipimagecollection'
            });
        });
    </script>
</div>

<div class="footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>[!ATOM]Published[ATOM!]</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>[!ATOM]Author[ATOM!]</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=[!ATOM]ID[ATOM!]">
                </form>
            </li>
        </ul>
    </div>
</div>
<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->

