<!DOCTYPE html>
<html lang="en">
<!-- include '../oip-modules/oip-head.txt' -->
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<!-- include 'oip-container-navbar-www-public.txt' -->
<div class="container">
    <section id="container-focus" class="well" >
        <?php include '../oip-modules/oip-module-activity-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.Activity -->
    </section>
</div>
<!-- include '../oip-containers/oip-container-footer.txt' -->
<!-- include '../oip-modules/oip-le-javascript.txt' -->
</body>
</html>
