<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->
<div class="header clearfix">
    <h2 class="clearfix">
        <!-- start oip-atom-title.txt -->
        <a data-id="87493283-5cba-4715-bf2d-d5a2eb3f8753_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a>
        <!-- end oip-atom-title.txt -->
        <br>
        <p>
            <img src="../../AaltoGlobalImpact.OIP/MediaContent/0157b2ac-e2bd-4e0a-a76b-d2faf53b0ca2_320x240_crop.jpg" />
        </p>
        <small>
            <!-- start oip-atom-subtitle.txt -->
            <a data-id="87493283-5cba-4715-bf2d-d5a2eb3f8753_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">First ACCESS event by AGI in Helsinki.</a>
            <!-- end oip-atom-subtitle.txt -->
        </small>
    </h2>
    <div class="btn-toolbar sharing-panel clearfix">
        <div class="btn-group">
            <a class="btn" href="#"><i class="icon-facebook"></i></a>
            <a class="btn" href="#"><i class="icon-linkedin"></i></a>
            <a class="btn" href="#"><i class="icon-twitter"></i></a>
            <a class="btn" href="#"><i class="icon-envelope"></i></a>
        </div>
    </div>
    <div class="border border-news clearfix">
        <span class="label label-news">News</span>
    </div>

</div>

<div class="content">
    <div class="multicolumnElement">
        <p align="left">Aalto Global Impact's first ACCESS event took place on April 19th in Helsinki.<br></p>
        <p align="left">It brought together some 100 participants from 12 countries (South Africa, Mozambique, Tanzania, Kenya, India, Sri Lanka, Nepal, Netherlands, Poland, United States, and Finland), including 25 students/volunteers from business and design.<br></p>
        <p align="left">The event led to 10 different topics of dialogue, out of which several are now materialising as global collaborative projects. The event also served to highlight and develop the work around themes and focus countries where collaboration already exists, or that we wish to explore further in the near future.<br></p>
        <p align="left">You may revisit the ACCESS event, its outputs and the people participating with the help of the following documentation:<br></p>
        <p align="left"></p>
        <ul>
            <li><span style="letter-spacing: 0.1em;">a short 4 min footage of the event: <a href="https://vimeo.com/41907787" title="ACCESS Helsinki 2012" target="_blank">https://vimeo.com/41907787</a></span><br></li>
            <li>a comprehensive presentation of the event, showing its process, its participants and what the groups have worked on: <a href="a comprehensive presentation of the event, showing its process, its participants and what the groups have worked on: https://www.dropbox.com/s/fwoxbgk09ic6wrt/AGI_Final.pdf" title="ACCESS Helsinki 2012" target="_blank">https://www.dropbox.com/s/fwoxbgk09ic6wrt/AGI_Final.pdf</a><br></li>
            <li>a selection of photos:&nbsp;https://www.dropbox.com/sh/ucgjk9c9sri7st3/vNj-Azxw4m<br></li><li>If you were a participant at the event, we welcome your feedback through this short questionnaire:&nbsp;<a href="https://docs.google.com/spreadsheet/viewform?formkey=dEZFTHk3OGhhZExERzVmM3plWUloV0E6MQ" title="Feedback" target="_blank">https://docs.google.com/spreadsheet/viewform?formkey=dEZFTHk3OGhhZExERzVmM3plWUloV0E6MQ</a>&nbsp;</li>
        </ul>
        <div>Date:Thursday 19th April, 2012&nbsp;</div>
        <div>Time:12.00 - 17.00&nbsp;</div>
        <div>Place:Aalto University, Lämppäri Building, Finlandia room, Lämpömiehenkuja 2, Espoo<br></div>
    </div>
</div>

<div class="media">
    <div id="flowcontainer" class="thumbnails">
        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->
    </div>
    <iframe src="http://player.vimeo.com/video/41907787?title=0&byline=0&portrait=0&color=ffffff" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/41907787">Aalto Global Impact ACCESS event</a> from <a href="http://vimeo.com/user11643087">Aalto Global Impact</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
    <script>
        $(function(){
            var $container = $('#flowcontainer');
            $container.isotope({
                itemSelector: '.oipimagecollection'
            });
        });
    </script>
</div>

<div class="footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 10:19:26 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=87493283-5cba-4715-bf2d-d5a2eb3f8753">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


