<!DOCTYPE html>
<html lang="en">
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.NodeSummaryContainer -->
<!-- THEBALL-CONTEXT-END:* -->
<?php include '../oip-modules/oip-head-map.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<script src="../oip-additions/oip-assets/oip-js/dust-full-1.1.1.js"></script>
<script src="../oip-additions/oip-assets/oip-js/xml2json.js"></script>
<?php include 'oip-container-navbar-www-public.txt' ?>

<script>
    function GetLayerLabelText(textvalue, iconUrl)
    {
        if(iconUrl != null)
            return "<img src='" + iconUrl + "' height='16' width='16'></img> " + textvalue;
        return textvalue;
    }

    $(function() {
        OipSetupDefaultMap = function(mapid, uselayers) {
            var map = L.map(mapid).setView([0, 0], 2);

            // add an OpenStreetMap tile layer
            var tileUrl = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';
            var tileAttribution = '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors';
            L.tileLayer(tileUrl, {
                attribution: tileAttribution
            }).addTo(map);

            // Marker arrays
            var ActivitiesMarkers = new Array();
            var ActivitiesMarkerIcon;
            var NewsMarkers = new Array();
            var NewsMarkerIcon;
            var ProjectsMarkers = new Array();
            var ProjectsMarkerIcon;
            var EventsMarkers = new Array();
            var EventsMarkerIcon;
            var BlogsMarkers = new Array();
            var BlogsMarkerIcon;

            // Cluster markers - only thing that has actual map-visible markers
            var markers = new L.MarkerClusterGroup();

            // Layers (empty per themselves, but control the toggling)
	
            var ActivitiesLayer = L.layerGroup();
            ActivitiesLayer.addTo(map);
            var NewsLayer = L.layerGroup();
            NewsLayer.addTo(map);
            var ProjectsLayer = L.layerGroup();
            ProjectsLayer.addTo(map);
            var EventsLayer = L.layerGroup();
            EventsLayer.addTo(map);
            var BlogsLayer = L.layerGroup();
            BlogsLayer.addTo(map);

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.MapContainer -->
            <?php include '../oip-modules/oip-module-leaflet-markers.txt' ?><!-- UseInformationObjectAsCollection:MapMarkers -->
<!-- THEBALL-CONTEXT-END:* -->
            var activitiesText = GetLayerLabelText("Activities", ActivitiesMarkerIcon);
            var newsText = GetLayerLabelText("News", NewsMarkerIcon);
            var projectsText = GetLayerLabelText("Projects", ProjectsMarkerIcon);
            var eventsText = GetLayerLabelText("Events", EventsMarkerIcon);
            var blogsText = GetLayerLabelText("Blogs", BlogsMarkerIcon);

            var overlayMaps = {
                /*
                    "Activities": ActivitiesLayer,
                    "News": NewsLayer,
                    "Projects": ProjectsLayer,
                    "Events": EventsLayer,
                    "Blogs": BlogsLayer,*/
            };
            overlayMaps[activitiesText] = ActivitiesLayer;
            overlayMaps[newsText] = NewsLayer;
            overlayMaps[projectsText] = ProjectsLayer;
            overlayMaps[eventsText] = EventsLayer;
            overlayMaps[blogsText] = BlogsLayer;


            // Adding marker arrays 
            markers.addLayers(ActivitiesMarkers);
            markers.addLayers(NewsMarkers);
            markers.addLayers(ProjectsMarkers);
            markers.addLayers(EventsMarkers);
            markers.addLayers(BlogsMarkers);
	
            map.addLayer(markers);
            markers.addTo(map);
	
            map.on("layeradd", function(e) {
                if(e.layer == ActivitiesLayer)
                    markers.addLayers(ActivitiesMarkers);
                if(e.layer == NewsLayer)
                    markers.addLayers(NewsMarkers);
                if(e.layer == ProjectsLayer)
                    markers.addLayers(ProjectsMarkers);
                if(e.layer == EventsLayer)
                    markers.addLayers(EventsMarkers);
                if(e.layer == BlogsLayer)
                    markers.addLayers(BlogsMarkers);
            });
            map.on("layerremove", function(e) {
                if(e.layer == ActivitiesLayer)
                    markers.removeLayers(ActivitiesMarkers);
                if(e.layer == NewsLayer)
                    markers.removeLayers(NewsMarkers);
                if(e.layer == ProjectsLayer)
                    markers.removeLayers(ProjectsMarkers);
                if(e.layer == EventsLayer)
                    markers.removeLayers(EventsMarkers);
                if(e.layer == BlogsLayer)
                    markers.removeLayers(BlogsMarkers);
            });

            L.control.layers(null, overlayMaps).addTo(map);
			map.invalidateSize(false);
        };
        /*OipSetupDefaultMap('map');*/
    });

</script> 

<div id="SelectedContentContainer" class="reading-pane">
</div>
<div class="container masonry" id="TileSection">
            Loading...
</div>
<script type="text/javascript">

	$(function() {
		OipCloseDetailPane = function() {
			$("#SelectedContentContainer").html('');
		};
		$(".oipmenuselector").on("click", function() {
			var filterName = $(this).data("filtername");
			var navigateto = $(this).data("locateto");
			//alert(navigateto);
			//var scrollPos = $(navigateto).offset().top;
			//$(document).animate({ scrollTop : $(navigateto).offset().top}, 'slow');
			//$(document).scrollTop($(navigateto).offset().top);
			OipCloseDetailPane();
			$("a[data-filter='" + filterName + "']").trigger('click');
			return false;
		});

		OipShowInDetailPaneWithClose = function(htmlContent) {
			$("#SelectedContentContainer").html('<div class="container"><section id="container-focus" class="well"><div class="reading-pane-header"><button id="paneclosebutton" type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>' +
				htmlContent + '</div></section></div>');
			$("#paneclosebutton").off("click");
			$("#paneclosebutton").click(OipCloseDetailPane);
		};
	});

    $(function () {
        $.get("../../AaltoGlobalImpact.OIP/NodeSummaryContainer/default", function (responseXml) {
            var dom;
            if (window.DOMParser) {
                parser = new DOMParser();
                dom = parser.parseFromString(responseXml, "text/xml");
            }
            else // Internet Explorer
            {
                dom = new ActiveXObject("Microsoft.XMLDOM");
                dom.async = false;
                dom.loadXML(responseXml);
            }
            var json = xml2json(dom, "  ");
            //alert(json);
            var myObj = jQuery.parseJSON(json);
            $.ajax({
                url: "oip-layout-landing.itemtmpl.html",
                //data: 'foo',
                cache: false,
                success: function (responseTemplate) {
                    var dynCompiled = dust.compile(responseTemplate, "nodeTmpl");
                    dust.loadSource(dynCompiled);
                    dust.render("nodeTmpl", myObj, function (err, out) {
                        $("#TileSection").html(out);
                    });
                }
            });
                    
        });
    });
</script>

<div class="container clearfix">
    <section class="well">
        <!-- '../oip-containers/oip-container-contact-oip.txt' --><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
