<!DOCTYPE html>
<html lang="en">
<?php include '../oip-modules/oip-head.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar-www-public.txt' ?>
<div class="container">
    <!-- oip-container-blog-focus-view.txt -->
	<section id="container-focus" class="container well" >
<?php include '../oip-containers/oip-container-blog.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer -->
	</section>
	<!-- oip-container-contact-oip.txt -->
	<section class="container well"> 
<?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
