<!DOCTYPE html>
<html lang="en">
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.NodeSummaryContainer -->
<!-- THEBALL-CONTEXT-END:* -->
<?php include '../oip-modules/oip-head-map.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<?php include 'oip-container-navbar-www-public.txt' ?>
<div class="container">
    <section id="container-focus" class="well">
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    <div class="span2 map-result-list">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
        </section>
</div>
<div class="container">
    <section class="well">
        <?php include '../oip-containers/oip-container-blog-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.BlogContainer  -->
    </section>
    <section class="well">
        <?php include '../oip-containers/oip-public-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <section class="well">
        <?php include '../oip-containers/oip-public-container-groups-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.GroupSummaryContainer  -->
    </section>
    <section class="well">
        <?php include '../oip-containers/oip-public-container-activities-summary.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ActivitySummaryContainer  -->
    </section>
    <section class="well">
        <?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
