<!DOCTYPE html>
<html lang="en">
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.NodeSummaryContainer -->
<!-- THEBALL-CONTEXT-END:* -->
<?php include '../oip-modules/oip-head-map.txt' ?>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<script src="../oip-additions/oip-assets/oip-js/dust-full-1.1.1.js"></script>
<script src="../oip-additions/oip-assets/oip-js/xml2json.js"></script>
<?php include 'oip-container-navbar-www-public.txt' ?>
<div class="container">
    <section id="container-focus" class="well">
        <?php include '../oip-containers/oip-container-map-focus-view.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.MapContainer-->
    <div class="span2 map-result-list">
        <?php include '../oip-modules/oip-module-map-result-list.txt' ?>
    </div>
        </section>
</div>
<div id="SelectedContentContainer">
</div>
<div class="masonry" id="ReplaceMyInner">
            Loading...
</div>
        <script type="text/javascript">

            $(function () {
                $.get("../../AaltoGlobalImpact.OIP/NodeSummaryContainer/default", function (responseXml) {
                //$.get("default-landing-page.html", function (responseXml) {
                    var dom = (new DOMParser()).parseFromString(responseXml, "text/xml");
                    var json = xml2json(dom, "  ");
                    //alert(json);
                    var myObj = jQuery.parseJSON(json);

                    var dynamicaddtempComp = dust.compile("Dynamic Template \"{HelloText}\" ", "dynamicaddtemp");
                    dust.loadSource(dynamicaddtempComp);
                    $.ajax({
                        url: "oip-layout-landing.itemtmpl.html",
                        //data: 'foo',
                        cache: false,
                        success: function (responseTemplate) {
                            var helloCompiled = dust.compile(responseTemplate, "hellodemo");
                            dust.loadSource(helloCompiled);
                            console.log("About demo begin");
                            dust.render("hellodemo", myObj, function (err, out) {
                                $("#ReplaceMyInner").html(out);
                            });
                            console.log("About demo out");
                        }
                    });
                    
                });
            });
        </script>

<div class="container">
    <section class="well">
        <?php include '../oip-containers/oip-public-container-about-collection.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.AboutContainer  -->
    </section>
    <section class="well">
        <?php include '../oip-containers/oip-container-contact-oip.txt' ?><!-- UseInformationObjectAsRoot:AaltoGlobalImpact.OIP.ContactOipContainer  -->
    </section>
</div>
<?php include '../oip-containers/oip-container-footer.txt' ?>
<?php include '../oip-modules/oip-le-javascript.txt' ?>
</body>
</html>
