<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/oip-bootstrap.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/bootstrap-responsive.css" rel="stylesheet">

    <!--  <link href="../bootstrap-default/assets/css/jdpicker.css" rel="stylesheet">-->
    <!--Extra Styles from jQuery UI-->
    <!--  <link href="../third-party/jquery-ui/css/demo.css" rel="stylesheet">
      <link href="../third-party/jquery-ui/css/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet"> -->
    <!-- calendar -->
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../oip-additions/oip-assets/oip-images/icons/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-144x144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-114x114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-72x72.png">
    <link rel="apple-touch-icon-precomposed" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-57x57.png">
    <script src="../oip-additions/oip-assets/oip-js/jquery.js"></script>
    <script src="../oip-additions/oip-assets/oip-js/OpenLayers.js"></script>
    <script type="text/javascript" src="../oip-additions/oip-assets/oip-js/nicEdit.js"></script>
</head>


<body data-spy="scroll" data-target=".subnav" data-offset="50" style="background-color:none">
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container oip-navbar">
            <ul class="nav">
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown"">
                    <span style="">Aalto Global Impact</span>
                    <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="../www-public/oip-layout-activities-summary.phtml">Homepage</a></li>
                        <li><a href="../www-public/oip-layout-map.phtml">Map</a></li>
                        <li><a href="../www-public/oip-layout-news.phtml">News</a></li>
                        <li><a href="../www-public/oip-layout-about.phtml">About</a></li>
                        <li><a href="../www-public/oip-layout-activities-summary.phtml"style="border: none;">Activities</a></li>
                    </ul>
                </li>
            </ul>
            </php><!-- navigation to www.aaltoglobalimpact.org -->
            <ul class="nav pull-right" style="margin-top: 0px">
                <li class="dropdown">
                    <a id="edittoggle"><i class="icon-pencil"></i> Edit</a> </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-user oip-account"></i>
                        My Account
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="oip-layout-account-welcome.phtml">Welcome Page</a></li>
                        <li><a href="oip-layout-account-edit.phtml">My Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="/TheBallLogin.aspx?SignOut=true">Logout</a></li>
                    </ul>
                </li>
            </ul></php><!-- edit and my account menus-->
        </div>
    </div>
</div>
<div class="subnavbar">
    <div class="subnavbar-inner navbar-account-border navbar-account-background">
        <div class="container">
            <ul class="mainnav">
                <li class="account" style="border: none">
                    <a href="" style="background-image: url(../oip-additions/oip-assets/oip-images/ui/oip-account-navbar-background.png);width: 200px"></a>
                </li>
                <li class="group-name" style="border-left: none">
                    <a href="#"> <img src="../oip-additions/oip-assets/oip-images/placeholder/andrew.png" width="60" height="60" alt="" class="img-polaroid" style="vertical-align:inherit;margin-top: 10px;height: 60px;width: 60px;margin-bottom: 0px;padding: 1px">
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-book oip-news"></i>
                        <span>News</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="alert"> Private view only </li>
                        <li> <a href="oip-layout-blog-summary.phtml"> Summary of My News Items</a></li>
                        <li> <a href="#add-blog" data-toggle="modal"> Add New News Item</a> </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-group oip-group"></i>
                        <span>Groups</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="alert"> Private view only </li>
                        <li> <a href="oip-layout-groups-summary.phtml"> Summary of My Groups</a> </li>
                        <li> <a href="#create-group" data-toggle="modal"> Create New Group</a> </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-bullhorn oip-activity"></i>
                        <span>Activities</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="alert"> Private view only </li>
                        <li> <a href="oip-layout-activities-summary.phtml"> Summary of My Activities</a> </li>
                        <li> <a href="#add-activity" data-toggle="modal"> Add New Activity</a> </li>
                    </ul>
                </li>
                <!--<li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-globe"></i>
                        <span>Our Public Site</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="../oip-public/oip-layout-landing.phtml" style="display: inline-table;clear: none"> Homepage </a>
                            <a href="#"  style="display: inline-table;padding-left:10px;padding-right:10px;text-align: left"><i class="icon-pencil"></i> Edit</a>
                        </li>
                        <li> <a href="../oip-public/oip-layout-map.phtml"> Map</a> </li>
                        <li> <a href="../oip-public/oip-layout-blog.phtml"> Blog</a> </li>
                        <li> <a href="../oip-public/oip-layout-about.phtml"> About</a> </li>

                        <li><a tabindex="-1" href="../oip-public/oip-layout-activities-summary.phtml.phtml"> Activities</a></li>
                        <li><a tabindex="-1" href="../oip-public/oip-layout-groups-summary.phtml.phtml"> Groups</a></li>
                        <li><a tabindex="-1" href="../oip-public/oip-layout-register.phtml"> Sign Up</a></li>
                    </ul>
                </li> -->
            </ul>
        </div>
    </div>
</div>

<!-- modals -->
<div id="create-group" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Create a group
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.CreateGroupInfo:CreateGroup -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="CreateGroup" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="a8474f97-deab-441d-afc8-23e77a140165_GroupName">Name of the group</label>
                    <div class="controls">
                        <input name="a8474f97-deab-441d-afc8-23e77a140165_GroupName" class="span4" id="a8474f97-deab-441d-afc8-23e77a140165_GroupName" type="text" value="">
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>

<div id="add-activity" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Add an activity
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddActivityInfo:AddActivity -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddActivity" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="573b052c-be18-41e7-b61b-c27c2b34c369_ActivityName">Add the activity's name'</label>
                    <div class="controls">
                        <input name="573b052c-be18-41e7-b61b-c27c2b34c369_ActivityName" class="span4" id="573b052c-be18-41e7-b61b-c27c2b34c369_ActivityName" type="text" value="">
                    </div>
                </div>

                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>


<div id="add-blog" class="modal hide fade">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2 class="title">
            Add a blog article
        </h2>
    </div>
    <div class="modal-body">
        <form method="post" class="form-horizontal">
            <!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.AddBlogPostInfo:AddBlogPost -->

            <!-- THEBALL-FORM-HIDDEN-FIELDS -->
            <input id="RootSourceName" name="RootSourceName" type="hidden" value="AddBlogPost" />
            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="22120272-9c46-445f-924d-2229e64e2c39_Title">Blog post's title</label>
                    <div class="controls">
                        <input name="22120272-9c46-445f-924d-2229e64e2c39_Title" class="span4" id="22120272-9c46-445f-924d-2229e64e2c39_Title" type="text" value="">
                    </div>
                </div>
                <div class="control-group controls">
                    <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                        <button value="true" name="btnCancel" class="btn">Cancel</button>
                        <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                    </div>
                </div>

            </fieldset>

            <!-- THEBALL-CONTEXT-END:* -->
        </form>
    </div>
</div>

<!-- end modals -->
<div class="container">
<section id="container-focus" class="container well" >

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.ActivitySummaryContainer -->

<div class="services oip-activity-header small">

    <!-- THEBALL-CONTEXT-OBJECT-BEGIN:Header -->

    <div class="hero-unit">
        <h1><a data-id="89fe9f0c-6aed-4e79-84eb-24ae218dbd07_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>

        </h1>
        <h1><small><span class="small-before-after"/>"</span>
            <a data-id="89fe9f0c-6aed-4e79-84eb-24ae218dbd07_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
            <span class="small-before-after"/>"</span>
        </small></h1>
    </div>



    <!-- THEBALL-CONTEXT-END:Header -->

</div>
<div class="row-fluid">
<div class="span3">

    <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ActivityIndex -->

    <p><img src="[!ATOM]ContentUrl[ATOM]"><br>This is the group's icon or brand image or logo</p>
    <h4></h4>
    <p></p>
    <p></p>

    <!-- THEBALL-CONTEXT-END:ActivityIndex -->

</div>
<div class="span9">
<div class="" style="margin-bottom: 40px">

    <!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

    <!-- oip-module-introduction.txt -->
    <h3>
        <a data-id="8669285a-57e1-4882-97a4-87d230b6ffb7_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>


    </h3>
    <p>
        <a data-id="8669285a-57e1-4882-97a4-87d230b6ffb7_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

    </p>
    <!-- end oip-module-introduction.txt -->


    <!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class>
<ul class="thumbnails">

<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ActivityCollection -->


<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/365328a7-b170-475b-9b1d-f4982ae11d47"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_26d14f39-2f3d-4bea-8957-539bf329bab7_DefaultView.phtml">Jeroen's activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/2ac28dc5-1fa5-4492-b830-e2b2dfd74b9f"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_6a9d2de3-851d-4fa2-aedb-d50a442f0adb_DefaultView.phtml">Jeroen's sixth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's sixth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/00942934-7487-4a8b-a3ca-1c3e77215e76"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_a9b9de9a-2f1c-446b-a73a-bfba97e7d364_DefaultView.phtml">Jeroen's eigth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's eigth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/34a5c1d4-7a30-4ffa-b25c-58f009ccacb4"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_b7e850ac-4ac6-4f06-b69b-9121cf6d445b_DefaultView.phtml">Jeroen's ninth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's ninth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/febd4c0f-ddd8-44cd-8e7b-1a34fe5b1b67"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_badf5cd6-ae52-4b4d-aaac-6d3302372af5_DefaultView.phtml">Jeroen's ninth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's ninth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/5a639654-0b7c-40fb-9f35-f224a15da566"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_bf322286-f633-445b-99f1-7e3364b5d590_DefaultView.phtml">Jeroen's second activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's second activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/b23b4bd9-4280-4763-aec3-f8aadb83abe7"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_c19c47e6-4988-4ab4-adf7-9a809408ba84_DefaultView.phtml">Jeroen's ninth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's ninth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/38aded00-65f8-47da-bdb7-e155ebeed95f"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_d02ad611-f7da-4fab-bc33-c94cdabc1f98_DefaultView.phtml">Jeroen's third activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's third activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/73c3f433-a97a-40bf-b8da-966cd904fc0b"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_df3ae845-17ee-42cc-9d83-1f2d683d4a55_DefaultView.phtml">Jeroen's fourth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's fourth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/156ea3e9-162a-44c4-aaaf-fa9876a2efe5"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_e688636d-b46b-4744-b017-bd24751b7354_DefaultView.phtml">Jeroen's seventh activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's seventh activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->

<li class="span3">
    <img class="img-style row1" src="AaltoGlobalImpact.OIP/MediaContent/0fc0ed86-58d7-4d5e-baad-d254f195b8a6"  />
    <h3>

        <!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

        <a href="AaltoGlobalImpact.OIP.Activity_ec9b959d-31af-43c6-b615-9337e2563f06_DefaultView.phtml">Jeroen's fifth activity on Wednesday 28th</a>


        <!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Jeroen's fifth activity on Wednesday 28th</small>
    </h3>
    <p><p>
</p>
    <ol class="unstyled">

        <!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->



    </ol>
</li>


<!-- THEBALL-CONTEXT-END:ActivityCollection -->


</ul>
<ul class="pager">
    <li class="previous">
        <a href="../oip-layouts/oip-layout-blog-more.phtml">&larr; Older</a>
    </li>
    <li class="next">
        <a href="../oip-layouts/oip-layout-blog-more.phtml">Newer &rarr;</a>
    </li>
</ul>
</div>

</div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.ActivitySummaryContainer -->

</section>
</div>
<footer class="footer">
    <div class="container"><div class="span12">
        <p class="pull-right"><a href="#">Back to top</a></p>
    </div>
        <div class="span4">
            <ul class="aalto-footer">
                <li >
                    <a href="http://www.aalto.fi/en">Aalto.fi</a>
                    <ul>
                        <li class="taik"><a href="http://arts.aalto.fi/en/">School of Arts, Design and Architecture</a></li>
                        <li class="hse"><a href="http://business.aalto.fi/en/">School of Business</a></li>
                        <li class="chem"><a href="http://chem.aalto.fi/en/">School of Chemical Technology</a></li>
                        <li class="elec"><a href="http://elec.aalto.fi/en/">School of Electrical Engineering</a></li>
                        <li class="eng"><a href="http://eng.aalto.fi/en/">School of Engineering</a></li>
                        <li class="sci"><a href="http://sci.aalto.fi/en/" style="border: none;">School of Science</a></li>
                    </ul>
                </li>
            </ul>        </div>
        <div class="span4">
            <p>Aalto Global Impact has been formed to bring together these existing parties working in societal issues and to help them develop their activities further</p>
        </div>
        <div class="span3">
            <p>The <a id="edittoggle">Open</a> Innovation Platform is offered to you by Aalto Global Impact, and Aalto University organisation</p>
            <p>All content licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
            <p>Icons from <a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        </div>
    </div>
</footer>


<!-- ========== Begin: oip-account\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->
<!-- oip-modal-collection.txt -->

<!-- ========== Begin: oip-account\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->
<!-- oip-modal-header.txt -->
<div class="modal hide fade well in-context-edit" id="IncontextEditDialog_Text_Short">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <input class="span4" type="text" name="Text_Short" id="Text_Short" value="" />

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-header.txt -->

<!-- ========== End: oip-account\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->


<!-- ========== Begin: oip-account\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->
<!-- oip-modal-text-long.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_Text_Long">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <textarea class="span5" rows="30" id="Text_Long" name="Text_Long"></textarea>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                </div>
            </div>

        </div>
    </form>
    <script type="text/javascript">
        function addRichTextEditTextLong() {
            richArea = new nicEditor({fullPanel : true, iconsPath : '../oip-additions/oip-assets/oip-js/nicEditorIcons.gif' }).panelInstance('Text_Long');
        }
        // Moved to actual dialog initiation script as the content weren't appearing from previous data
        // bkLib.onDomLoaded(function() { addRichTextEditTextLong(); });
    </script>
</div>
<!-- end oip-modal-text-long.txt -->

<!-- ========== End: oip-account\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->


<!-- ========== Begin: oip-account\..\oip-containers\..\oip-modals\oip-modal-radiogroup.txt ========== -->
<!-- oip-modal-radiogroup.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_RadioGroup">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
        <div class="modal-body">
            <div class="control-group">
                <label class="checkbox">
                    <input type="radio" id="LocationName" name="_LocationName" value="_LocationName">LocationName</label>
            </div>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-radiogroup.txt -->

<!-- ========== End: oip-account\..\oip-containers\..\oip-modals\oip-modal-radiogroup.txt ========== -->


<!-- ========== Begin: oip-account\..\oip-containers\..\oip-modals\oip-modal-multiselect.txt ========== -->
<!-- oip-modal-multiselect.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_MultiSelect">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <div class="control-group">
                <label class="control-label" for="multiSelect"> Assign category </label>
                <div class="controls">
                    <select multiple="multiple" id="multiSelect" size="12">
                        <optgroup label="Projects">
                            <option> Projects </option>
                            <option selected="selected"> Finland </option>
                            <option> South America </option>
                            <option> Africa </option>
                        </optgroup> <optgroup label="Events">
                        <option selected="selected"> Events </option>
                        <option> Seminar </option>
                        <option selected="selected"> Conference </option>
                        <option> Meeting </option>
                    </optgroup> <optgroup label="Courses">
                        <option> Courses </option>
                        <option> Ba </option>
                        <option> MA </option>
                        <option> Design </option>
                    </optgroup> <optgroup label="Research">
                        <option> Research </option>
                        <option> BoP </option>
                        <option selected="selected"> Inclusive Business </option>
                    </optgroup>
                    </select>
                </div>
            </div>

            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
                    <button value="true" name="btnCancel" class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary" name="RootSourceAction" value="Save">Save changes</button>
                </div>
            </div>

        </div>
    </form>
</div>
<!-- end oip-modal-multiselect.txt -->

<!-- ========== End: oip-account\..\oip-containers\..\oip-modals\oip-modal-multiselect.txt ========== -->

<div class="modal hide fade well in-context-edit" id="IDAction_ConfirmRemove">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <form method="post">
        <div class="modal-body">
            <input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
            <p name="question" id="question">Not set</p>
            <div class="control-group controls">
                <div class="form-actions" style="padding:0;margin:0;border-top:0;background-color: transparent">
                    <button value="true" name="btnCancel"  class="btn">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-danger" name="RootSourceAction" id="RootSourceAction" value="Delete">Delete</button>
                </div>
            </div>

        </div>
    </form>
</div>

<div class="modal hide fade well" id="IDRemoteUrlModal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">close</button>
    </div>
    <div id="IDRemoteUrlModalBody">
        Loading content...
    </div>
</div>

<!-- end oip-modal-collection.txt -->
<!-- ========== End: oip-account\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->



<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-transition.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-alert.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-modal.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-dropdown.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-scrollspy.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tab.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tooltip.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-popover.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-button.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-collapse.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-carousel.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-typeahead.js"></script>
<!-- calendar -->
<script src="../oip-additions/oip-assets/oip-js/third-party-calendar.js"></script>
<!-- OIP specific -->
<script src="../oip-additions/oip-assets/oip-js/in-context-editing.js"></script>
<script src="../oip-additions/oip-assets/oip-js/modal-id-actions.js"></script>
</body>
</html>

